### ISSUE TITLE
CompCert 2.7.1 doesn't build under cygwin (menhir problem)

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#108]
I can't build CompCert 2.7.1 under cygwin on Windows 10.
The problem is that it requires menhir-2016xxxx.
This version of menhir doesn't build (although menhir-2015xxx did build),
because:

[from the Menhir "make"]:
Checking that OCaml is recent enough...
Cannot load required shared library dllcamlstr.
Reason: dllcamlstr.so: dynamic loading not supported on this platform.
File "checkOCamlVersion.ml", line 1:
Error: Reference to undefined global `Str'
Makefile:46: recipe for target '.versioncheck' failed

I have "The OCaml compiler, version 4.02.3".

I'm reporting this menhir problem to Francois Pottier.

Meanwhile, it's very annoying that every time I install a new
version of CompCert, I have to install a new menhir.
I BEG AND PLEAD WITH YOU:  Distribute the OUTPUT of menhir
in the CompCert source distribution (and in the github repo).
That way, the 99% of us that do not need to change the C grammar,
will not need menhir.

**Comment by bschommer** [comment]
The problem seems to be a configure check of Menhir. Just remove:
`@ ocaml checkOCamlVersion.ml --verbose --gt "4.02"`
from the .versioncheck goal in src/Makefile.

Including the generated files is unfortunately not possible due to our customer requirements.

**Comment by jhjourdan** [comment]
Maybe we could release the menhir generated files in a separate tarball for the same release ?

**Comment by andrew-appel** [comment]
Removing the "ocaml checkOCamlVersion.ml" solves the problem.  Thank you.

**Comment by bschommer** [comment]
I think the original issue was more a menhir problem than a CompCert issue and normally menhir should build under windows, since we are also relying on a working menhir build.
