### ISSUE TITLE
Fatal error: exception File "cparser/StructReturn.ml", line 488, characters 10-16: Assertion failed

### ISSUE THREAD

**Issue by chengniansun** [AbsInt/CompCert#111]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1
$ ccomp -fall small.c
small.c:1: Warning: empty struct.
small.c:7: Error: return value has type struct inode *
  instead of the expected type struct inode.
Fatal error: exception File "cparser/StructReturn.ml", line 488, characters 10-16: Assertion failed
Raised at file "cparser/StructReturn.ml", line 488, characters 10-22
Called from file "cparser/StructReturn.ml", line 561, characters 9-69
Called from file "cparser/Transform.ml", line 210, characters 19-33
Called from file "cparser/Parse.ml", line 22, characters 11-157
Called from file "cparser/Parse.ml", line 77, characters 6-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 72, characters 12-41
Called from file "driver/Driveraux.ml", line 118, characters 34-40
Called from file "driver/Driver.ml", line 547, characters 22-70
$ cat small.c
struct inode {};
struct afs_vnode {
  struct inode vfs_inode;
};
struct inode fn1() {
  struct afs_vnode *vnode;
  return &vnode->vfs_inode;
}
$

**Comment by bschommer** [comment]
Is fixed by commit b184e05aada74f34dafd9d1bf6bc24e68ab76e05
