### ISSUE TITLE
Fatal error: exception Elab.Wrong_attr_arg Raised at file "cparser/Elab.ml", line 392, characters 19-33

### ISSUE THREAD

**Issue by helloqirun** [AbsInt/CompCert#115]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1

$ ccomp -interp -fall abc.c
abc.c:1: Error: incomplete type void(void).
Fatal error: exception Elab.Wrong_attr_arg
Raised at file "cparser/Elab.ml", line 392, characters 19-33
Called from file "cparser/Elab.ml", line 433, characters 18-41
Called from file "cparser/Elab.ml", line 489, characters 29-49
Called from file "list.ml", line 73, characters 12-15
Called from file "cparser/Elab.ml", line 507, characters 2-34
Called from file "cparser/Elab.ml", line 723, characters 4-51
Called from file "cparser/Elab.ml", line 2166, characters 8-52
Called from file "cparser/Elab.ml", line 2181, characters 26-54
Called from file "cparser/Elab.ml", line 2436, characters 9-63
Called from file "cparser/Parse.ml", line 76, characters 15-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 135, characters 22-56
Called from file "driver/Driveraux.ml", line 118, characters 34-40
Called from file "driver/Driver.ml", line 547, characters 22-70

$ cat abc.c
_Alignas (void (void)) char e;

**Comment by bschommer** [comment]
Fixed by commit b1a059251053a061d98e4b440bfab40ffd8761c7.
