### ISSUE TITLE
Fatal error: exception File "cparser/Cutil.ml", line 1056, characters 6-12: Assertion failed

### ISSUE THREAD

**Issue by helloqirun** [AbsInt/CompCert#119]
This happens on the latest trunk version commit e2b4459c.

BTW, is there a way to show the commit number in the command line?

$ ccomp -version
The CompCert C verified compiler, version 2.7.1

$ ccomp-trunk -interp -fall abc.c
Fatal error: exception File "cparser/Cutil.ml", line 1056, characters 6-12: Assertion failed
Raised at file "cparser/Cutil.ml", line 1056, characters 6-18
Called from file "cparser/Elab.ml", line 1009, characters 41-60
Called from file "cparser/Elab.ml", line 1290, characters 13-37
Called from file "cparser/Elab.ml", line 1299, characters 11-41
Called from file "cparser/Elab.ml", line 1317, characters 8-39
Called from file "cparser/Elab.ml", line 1946, characters 23-58
Called from file "list.ml", line 84, characters 24-34
Called from file "cparser/Elab.ml", line 1962, characters 22-62
Called from file "cparser/Elab.ml", line 2186, characters 26-54
Called from file "cparser/Elab.ml", line 2441, characters 9-63
Called from file "cparser/Parse.ml", line 76, characters 15-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 135, characters 22-56
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 548, characters 22-70

$ cat abc.c
 void a = abc;

**Comment by bschommer** [comment]
You can append the commit number to the version in the VERSION file.

**Comment by bschommer** [comment]
Fixed by commit f26267c6289e4fa306a0875ff149a00ee401e043.
