### ISSUE TITLE
Fatal error: exception Env.Error "Unbound struct 'S'" 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#120]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1
$ 
$ ccomp small.c
small.c:1: Error: incomplete type struct S.
Fatal error: exception Env.Error "Unbound struct 'S'"
Raised at file "cparser/Env.ml", line 173, characters 9-48
Called from file "cparser/Cutil.ml", line 147, characters 15-36
Called from file "cparser/Cutil.ml", line 408, characters 28-54
Called from file "cparser/Ceval.ml", line 244, characters 18-32
Called from file "cparser/Ceval.ml", line 267, characters 41-53
Called from file "cparser/Elab.ml", line 625, characters 18-45
Called from file "cparser/Elab.ml", line 727, characters 6-49
Called from file "cparser/Elab.ml", line 93, characters 24-32
Called from file "cparser/Elab.ml", line 734, characters 3-35
Called from file "cparser/Elab.ml", line 2171, characters 8-52
Called from file "cparser/Elab.ml", line 2186, characters 26-54
Called from file "cparser/Elab.ml", line 2441, characters 9-63
Called from file "cparser/Parse.ml", line 76, characters 15-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 72, characters 12-41
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 548, characters 22-70
$ 
$ cat small.c
int a[__alignof__(struct S)];
$

**Comment by zhendongsu** [comment]
Formatting has messed up the code, which should have been: 

`int a[__alignof__(struct S)];`

**Comment by bschommer** [comment]
Fixed by commit 98427e8d2e51b1b7590bbde3fc18c49ff7dd8e13.

**Comment by zhendongsu** [comment]
Thanks for the fix, @bschommer! 

BTW, are you able to reproduce #113?   I see that it's still open after a few days.

**Comment by m-schmidt** [comment]
Yes we can reproduce it. Fix in in the works.

**Comment by zhendongsu** [comment]
Great; thanks.

**Comment by xavierleroy** [comment]
Please don't rush.  I'd like to look at #113 myself but I am currently busy with the death of a close relative.

**Comment by m-schmidt** [comment]
Regarding this problem: I had a look into IRC.ml. Is it legal to call "IRC.add_pref g a b" with a and b being the same variable?

Michael Schmidt

**Comment by xavierleroy** [comment]
We really need to move this discussion out of this report.  Commit 0a7288f plausibly fixes the issue with #113.

Concerning `IRC.add_pref a b`, I don't think anything goes wrong if `a = b`.  Eventually, `IRC.coalesce` will drop this move.  But clearly this is wasteful in memory (more moves are recorded) and perhaps in speed of register allocation, so we should shortcut this case.
