### ISSUE TITLE
Fatal error: exception Invalid_argument("Fatal error: va_start used in non-vararg function")

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#126]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit 3e1ceff)
$ 
$ ccomp small.c
Fatal error: exception Invalid_argument("Fatal error: va_start used in non-vararg function")
Raised at file "pervasives.ml", line 31, characters 25-45
Called from file "ia32/Asmexpand.ml", line 204, characters 4-67
Called from file "list.ml", line 73, characters 12-15
Called from file "ia32/Asmexpand.ml", line 447, characters 6-45
Called from file "ia32/Asmexpand.ml", line 454, characters 18-38
Called from file "extraction/AST.ml", line 366, characters 12-27
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 368, characters 15-55
Called from file "extraction/AST.ml", line 391, characters 8-57
Called from file "driver/Driver.ml", line 53, characters 10-123
Called from file "driver/Driver.ml", line 73, characters 2-36
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 548, characters 22-70
$ 
$ cat small.c
#include <stdarg.h>

void foo (int a)
{
  va_list vp;
  va_start (vp, a);
} 
$

**Comment by bschommer** [comment]
Fixed by commit cc2d157be19d52bbe666e6d5a7ee9879cff7bfc8.
