### ISSUE TITLE
C to CompCert C transformation for variadic functions 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#127]
The produced CompCert C code 

void foo(int a...)

seems to should have been

void foo(int a, ...)

(i.e., a comma ',' is missing). 

$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit 3e1ceff)
$   
$ ccomp -dc -c test.c
$ 
$ cat test.c
void foo (int a, ...) { /* skip */ }
$ 
$ cat test.compcert.c
extern unsigned int __compcert_va_int32(void *);

extern unsigned long long __compcert_va_int64(void *);

extern double __compcert_va_float64(void *);

extern void *__compcert_va_composite(void *, unsigned int);

extern long long __i64_dtos(double);

extern unsigned long long __i64_dtou(double);

extern double __i64_stod(long long);

extern double __i64_utod(unsigned long long);

extern float __i64_stof(long long);

extern float __i64_utof(unsigned long long);

extern long long __i64_sdiv(long long, long long);

extern unsigned long long __i64_udiv(unsigned long long, unsigned long long);

extern long long __i64_smod(long long, long long);

extern unsigned long long __i64_umod(unsigned long long, unsigned long long);

extern long long __i64_shl(long long, int);

extern unsigned long long __i64_shr(unsigned long long, int);

extern long long __i64_sar(long long, int);

extern void __builtin_debug(int, ...);

void foo(int a...)
{
  /*skip*/;
}

$

**Comment by bschommer** [comment]
Is fixed by commit aa5ddeddbe50487f6671b80d1a58a09d619d6f66.
