### ISSUE TITLE
C to CompCert C transformation removes prototypes (intended?) 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#128]
I'm unclear whether the following is the intended behavior, but I had expected: if test.c compiles, then test.compcert.c should also compile (and exhibit the same behavior). 

$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit 3e1ceff)
$ 
$ ccomp -dc -c test.c
$ 
$ ccomp -c test.compcert.c      
test.compcert.c:39: Warning: implicit declaration of function 'f'.
test.compcert.c:42: Error: redefinition of 'f' with incompatible type.
  Previous declaration: int f(). New declaration: void f(int b).
1 error detected.
$ 
$ cat test.c
void f (int); 
void g (int a) { f (0); }
void f (int b) { /* skip */ }
$ 
$ cat test.compcert.c
extern unsigned int __compcert_va_int32(void *);

extern unsigned long long __compcert_va_int64(void *);

extern double __compcert_va_float64(void *);

extern void *__compcert_va_composite(void *, unsigned int);

extern long long __i64_dtos(double);

extern unsigned long long __i64_dtou(double);

extern double __i64_stod(long long);

extern double __i64_utod(unsigned long long);

extern float __i64_stof(long long);

extern float __i64_utof(unsigned long long);

extern long long __i64_sdiv(long long, long long);

extern unsigned long long __i64_udiv(unsigned long long, unsigned long long);

extern long long __i64_smod(long long, long long);

extern unsigned long long __i64_umod(unsigned long long, unsigned long long);

extern long long __i64_shl(long long, int);

extern unsigned long long __i64_shr(unsigned long long, int);

extern long long __i64_sar(long long, int);

extern void __builtin_debug(int, ...);

void g(int a)
{
  f(0);
}

void f(int b)
{
  /*skip*/;
}

$

**Comment by bschommer** [comment]
This was indeed not intended. The problem was that with the missing declaration f is considered to be an implicit function declaration and the types conflict with the later definition.
Fixed by commit 97ef3561168a6262833e65aba379ab9aca1a1a17.
