### ISSUE TITLE
Unsupported feature: wide string literal

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#13]
As a followup to issue #6:

    $ cat foo.c
    #include <wchar.h>
    
    int main() {
            wcschr(L"abcd", L'c');
    }
    $ ccomp -fall foo.c
    foo.c:4: Unsupported feature: wide string literal

**Comment by xavierleroy** [comment]
Indeed the final translation of wide string literals to initialized arrays of wchar_t was missing.  Added in commit [master d1104c0].
