### ISSUE TITLE
C to CompCert C transformation omits library functions 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#130]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit c64c4ab)
$ 
$ ccomp -dc small.c
$ ccomp small.compcert.c
small.compcert.c:42: Warning: implicit declaration of function 'malloc'.
small.compcert.c:42: Warning: assigning a value of type int
  to a lvalue of type int *.
small.compcert.c:42: Warning: 'malloc' is declared without a function prototype.
small.compcert.c: In function malloc: Cshmgen.transl_fundef: wrong external signature
$ 
$ cat small.c
#include <stdlib.h>

int main ()
{
  int *p = malloc (sizeof(int)); 
  return 0; 
}
$ cat small.compcert.c
extern int main(void);

extern unsigned int __compcert_va_int32(void *);

extern unsigned long long __compcert_va_int64(void *);

extern double __compcert_va_float64(void *);

extern void *__compcert_va_composite(void *, unsigned int);

extern long long __i64_dtos(double);

extern unsigned long long __i64_dtou(double);

extern double __i64_stod(long long);

extern double __i64_utod(unsigned long long);

extern float __i64_stof(long long);

extern float __i64_utof(unsigned long long);

extern long long __i64_sdiv(long long, long long);

extern unsigned long long __i64_udiv(unsigned long long, unsigned long long);

extern long long __i64_smod(long long, long long);

extern unsigned long long __i64_umod(unsigned long long, unsigned long long);

extern long long __i64_shl(long long, int);

extern unsigned long long __i64_shr(unsigned long long, int);

extern long long __i64_sar(long long, int);

extern void __builtin_debug(int, ...);

int main(void)
{
  int *p;
  p = malloc(sizeof(int));
  return 0;
  return 0;
}

$

**Comment by bschommer** [comment]
Fixed by commit b55d63d2917b384fa0f5da76d7d16036ad263847.
