### ISSUE TITLE
C to CompCert C transformation error for variadic functions 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#131]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit c64c4ab)
$ 
$ ccomp -dc -c small.c
$ 
$ ccomp -c small.compcert.c
small.compcert.c:45: Error: bad use of a va_list object.
1 error detected.
$ 
$ cat small.c
#include <stdarg.h>

void f (int n, ...)
{
  int s = 0;
  va_list ap;
  va_start (ap, n);
  for (int i = 0; i < n; i++)
    s += va_arg (ap, int);
  va_end (ap);
}
$ 
$ cat small.compcert.c
extern void f(int, ...);

extern unsigned int __compcert_va_int32(void *);

extern unsigned long long __compcert_va_int64(void *);

extern double __compcert_va_float64(void *);

extern void *__compcert_va_composite(void *, unsigned int);

extern long long __i64_dtos(double);

extern unsigned long long __i64_dtou(double);

extern double __i64_stod(long long);

extern double __i64_utod(unsigned long long);

extern float __i64_stof(long long);

extern float __i64_utof(unsigned long long);

extern long long __i64_sdiv(long long, long long);

extern unsigned long long __i64_udiv(unsigned long long, unsigned long long);

extern long long __i64_smod(long long, long long);

extern unsigned long long __i64_umod(unsigned long long, unsigned long long);

extern long long __i64_shl(long long, int);

extern unsigned long long __i64_shr(unsigned long long, int);

extern long long __i64_sar(long long, int);

extern void __builtin_debug(int, ...);

void f(int n,...)
{
  int s;
  void *ap;
  int i;
  s = 0;
  __builtin_va_start(&ap);
  i = 0;
  for (/*nothing*/; i < n; i++) {
    s += (int) __compcert_va_int32(&ap);
  }
  (void) 0;
}

$

**Comment by xavierleroy** [comment]
There might be a misunderstanding here.

The "CompCert C" output of CompCert is intended to help with using the reference interpreter (see chapter 4 of the manual) and with debugging the C front-end.

There is no guarantee whatsoever that the `.compcert.c` output is valid, portable, standard-conformant ISO C99 code.  

CompCert does a best effort to make the output look like C code, for ease of reading, but in the end it is CompCert C abstract syntax that is displayed.  Moreover, it contains implementation tricks that are not portable C code but are specific to CompCert, such as the emulation of vararg functions in your example above.  

So, I don't think it makes sense to test the `.compcert.c` output of CompCert with another compiler and to report every surprise as a bug on this bug tracker.

**Comment by zhendongsu** [comment]
Thanks for the clarifications, Xavier.  But should one at least expect the .compcert.c output to work with CompCert itself, which is what this test illustrates?

**Comment by xavierleroy** [comment]
> But should one at least expect the .compcert.c output to work with CompCert itself, which is what this test illustrates? 

That's a more modest objective indeed, but at this point it remains a best effort and not a property I want to commit on.  Especially for C features such as varargs (or extended inline assembly, to take another of your reports as an example) that lie squarely outside of CompCert's formally specified and verified core.

**Comment by zhendongsu** [comment]
I guess that's fair, Xavier; thank you.
