### ISSUE TITLE
C to CompCert C transformation: argv's type in main (char ** vs. signed char **)

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#132]
Not sure whether or not this is an issue, but it does seem that char (whose signedness is implementation-specified), signed char, and unsigned char are different types in C. 

So, perhaps for compatibility, it would be good to have the signature of main to be outputted as: 

int main (int argc, char **argv)

rather than

int main (int argc, signed char **argv)
?

$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit b55d63d)
$ 
$ ccomp -dc test.c
$ ccomp test.compcert.c
$ 
$ clang-trunk test.c
test.c:1:5: error: second parameter of 'main' (argument array) must be of type 'char **'
int main (int argc, signed char **argv)
    ^
1 error generated.
$ 
$ gcc-trunk test.c -Wall -Wextra -pedantic -std=c99 
test.c:1:5: warning: second argument of ‘main’ should be ‘char **’ [-Wmain]
 int main (int argc, signed char **argv)
     ^~~~
test.c: In function ‘main’:
test.c:1:15: warning: unused parameter ‘argc’ [-Wunused-parameter]
 int main (int argc, signed char **argv)
               ^~~~
test.c:1:35: warning: unused parameter ‘argv’ [-Wunused-parameter]
 int main (int argc, signed char **argv)
                                   ^~~~
$ 
$ cat test.c
int main (int argc, signed char **argv)
{
  return 0; 
}
$

**Comment by xavierleroy** [comment]
CompCert C has a `signed char` type and an `unsigned char` type, but no `char` type.  That's the way it should be.  See also my comments on issue #131 : CompCert C is not ISO C.

**Comment by zhendongsu** [comment]
Okay Xavier, thanks for the explanation.
