### ISSUE TITLE
Fatal error: exception Env.Error "'S' was declared as a struct but is used as a union" 

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#133]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit 0a7288f)
$ 
$ ccomp -c small.c
Fatal error: exception Env.Error "'S' was declared as a struct but is used as a union"
Raised at file "cparser/Env.ml", line 179, characters 11-60
Called from file "cparser/Cutil.ml", line 149, characters 15-35
Called from file "cparser/Elab.ml", line 1728, characters 25-57
Called from file "cparser/Elab.ml", line 2261, characters 19-55
Called from file "cparser/Elab.ml", line 2437, characters 19-38
Called from file "cparser/Elab.ml", line 2421, characters 13-54
Called from file "cparser/Elab.ml", line 2450, characters 5-26
Called from file "cparser/Elab.ml", line 2137, characters 14-53
Called from file "cparser/Elab.ml", line 2182, characters 17-56
Called from file "cparser/Elab.ml", line 2203, characters 26-54
Called from file "cparser/Elab.ml", line 2204, characters 26-56
Called from file "cparser/Elab.ml", line 2204, characters 26-56
Called from file "cparser/Elab.ml", line 2460, characters 9-63
Called from file "cparser/Parse.ml", line 76, characters 15-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 72, characters 12-41
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 550, characters 22-70
$ 
$ cat small.c
struct S { int x; };

union S *u, v; 

void f () 
{
  *u = v;
}
$

**Comment by bschommer** [comment]
Fixed by commit 640babdc9ea0958de967ce8b5ac84bb0309b3835.
