### ISSUE TITLE
Fatal error: exception File "cparser/Bitfields.ml", line 295, characters 6-12: Assertion failed

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#136]
$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit ec95665)
$ 
$ ccomp -fall small.c
Fatal error: exception File "cparser/Bitfields.ml", line 295, characters 6-12: Assertion failed
Raised at file "cparser/Bitfields.ml", line 295, characters 6-18
Called from file "cparser/Bitfields.ml", line 323, characters 13-38
Called from file "cparser/Bitfields.ml", line 322, characters 29-62
Called from file "cparser/Bitfields.ml", line 335, characters 12-61
Called from file "cparser/Bitfields.ml", line 503, characters 24-60
Called from file "cparser/Bitfields.ml", line 510, characters 52-71
Called from file "cparser/Transform.ml", line 208, characters 17-29
Called from file "cparser/Parse.ml", line 25, characters 2-38
Called from file "cparser/Parse.ml", line 78, characters 6-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 72, characters 12-41
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 550, characters 22-70
$ 
$ cat small.c
struct 
{
  int f:1;
  int f[1];
} a = { 0, { 0 } };
$

**Comment by bschommer** [comment]
Fixed by commit 55fa31e474c0f039330d6325ab33bbd86522d084.
