### ISSUE TITLE
Fatal error: exception Env.Error "Unbound struct 'S'"

### ISSUE THREAD

**Issue by zhendongsu** [AbsInt/CompCert#138]
The test is old-style K&R code. 

$ ccomp -version
The CompCert C verified compiler, version 2.7.1 (commit ec95665)
$ 
$ ccomp small.c
small.c:1: Warning: Non-prototype, pre-standard function definition.
   Converting to prototype form.
Fatal error: exception Env.Error "Unbound struct 'S'"
Raised at file "cparser/Env.ml", line 173, characters 9-48
Called from file "cparser/Cutil.ml", line 486, characters 15-39
Called from file "cparser/Cutil.ml", line 556, characters 21-33
Called from file "cparser/Cutil.ml", line 805, characters 13-37
Called from file "cparser/Elab.ml", line 1619, characters 17-47
Called from file "cparser/Elab.ml", line 1761, characters 18-48
Called from file "cparser/Elab.ml", line 2264, characters 19-55
Called from file "cparser/Elab.ml", line 2440, characters 19-38
Called from file "cparser/Elab.ml", line 2424, characters 13-54
Called from file "cparser/Elab.ml", line 2453, characters 5-26
Called from file "cparser/Elab.ml", line 2140, characters 14-53
Called from file "cparser/Elab.ml", line 2185, characters 17-56
Called from file "cparser/Elab.ml", line 2206, characters 26-54
Called from file "cparser/Elab.ml", line 2463, characters 9-63
Called from file "cparser/Parse.ml", line 76, characters 15-59
Called from file "driver/Frontend.ml", line 58, characters 10-59
Called from file "driver/Driver.ml", line 72, characters 12-41
Called from file "driver/Driveraux.ml", line 140, characters 34-40
Called from file "driver/Driver.ml", line 550, characters 22-70
$ 
$ cat small.c
void f ( p )
     struct S { int x; } *p;
{ 
  p += 4; 
}
$

**Comment by bschommer** [comment]
Fixed by commit 64a1e734dfe24194bafd33cff1fbe4d9e1cfdf14.
