### ISSUE TITLE
CompCert command line parsing vs. gcc

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#14]
The following command line fails:

    $ ccomp -Wl,shared -o libwhatever.so.1.1 X.so Y.so
    Unknown argument `X.so'

Renaming *.so to *.o works fine:

    $ ccomp -Wl,shared -o libwhatever.so.1.1 X.o Y.o
    $

gcc works with both cases.

**Comment by xavierleroy** [comment]
Tentative fix in commit [master 334be23]: .so arguments are passed to the linker just like .o arguments.  It could be that GCC passes all unrecognized arguments to the linker, but I'm afraid to implement the same behavior in CompCert by fear of getting really mysterious error messages.
