### ISSUE TITLE
another menhir problem (dll error, target is too far)

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#141]
I am trying to build CompCert 2.7.1 on Windows 10 (64-bit) under cygwin.
As usual, first I have to build/install menhir.
As usual, menhir fails for a new reason.  (It's always a new reason).

I have installed CompCert dozens of times in my life.
The number of times I have modified the grammer: zero.
I beg again for the CompCert distribution to be equipped with the menhir output, so that anyone can run CompCert without having to install menhir.

The specific problem with menhir this time is shown below:
compiling/linking the menhir source code fails.

$ make PREFIX=/usr/local USE_OCAMLFIND=false all
make[1]: Entering directory '/cygdrive/c/Local/menhir-20160825/src'
ocamlbuild -classic-display -j 0 -cflags "-safe-string -bin-annot" menhirLib.cmo menhirLib.cmx
# No parallelism done
Checking that OCaml is recent enough...
/usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild.exe
/usr/bin/ocamldep.opt -modules checkOCamlVersion.ml > checkOCamlVersion.ml.depends
/usr/bin/ocamlc.opt -c -safe-string -bin-annot -g -o checkOCamlVersion.cmo checkOCamlVersion.ml
/usr/bin/ocamlc.opt str.cma -g checkOCamlVersion.cmo -o checkOCamlVersion.byte
+ /usr/bin/ocamlc.opt str.cma -g checkOCamlVersion.cmo -o checkOCamlVersion.byte
File "_none_", line 1:
Error: Error on dynamically loaded library: /usr/lib/ocaml/stublibs/dllcamlstr.so: flexdll error: cannot relocate RELOC_REL32, target is too far: 0xfffffffc1de7020a  0x1de7020a
Command exited with code 2.
make[1]: *** [Makefile:53: .versioncheck] Error 10
make[1]: Leaving directory '/cygdrive/c/Local/menhir-20160825/src'
make: *** [Makefile:119: all] Error 2

**Comment by jhjourdan** [comment]
As a quick fix, have you tried an older version of menhir (one that did work)?
CompCert's grammar had very few changes recently, so there should not be any compatibility issue.

But anyway, this seems to be an OCaml-related problem that some other people had previously:

 https://cygwin.com/ml/cygwin-apps/2016-04/msg00035.html

**Comment by andrew-appel** [comment]
The menhir website does not list the previous distribution versions, only the current one.

**Comment by jhjourdan** [comment]
Well, that's not very difficult to get an old version : you can go to the changelog to get the list of old versions:

 http://gallium.inria.fr/~fpottier/menhir/CHANGES

And then get a particular version. For example:

http://gallium.inria.fr/~fpottier/menhir/menhir-20160415.tar.gz

**Comment by bschommer** [comment]
I don't thing that using an older version of menhir will help here. The problem seems to me that the cygwin ocaml packages are broken as described in the links of @jhjourdan.

**Comment by bschommer** [comment]
As an intermediate fix you can again patch out the version check.

**Comment by ludwigschreier** [comment]
Hi @andrew-appel, I hope in the meantime you built your version, but I'm actually running into similar difficulties building everything on Linux. Luckily it seems menhir is part of latest Ubuntu Linux apt sources, so that would install it directly. Building menhir in Linux myself failed also several times, so I tried the packaged version which seems OK. How about OPAM for Cygwin? Kind regards

**Comment by bschommer** [comment]
It seems strange that menhir does not compile under Linux. The only reason I could imagine is that potentially the system ocaml is to old. Under Linux I would recommend using opam instead of relying on the packages.

Concerning general menhir problems: It is best to report them on the [menhir mailing list](https://sympa.inria.fr/sympa/info/menhir).

**Comment by ludwigschreier** [comment]
Thanks for quick reply. And then there is this, which is very new just now:

```
...
make -f Makefile.extr ccomp
make[2]: Entering directory '/media/psf/iCloud/ludwigcloud/dev/compcert/CompCert-2.6'
ocamlfind: Package `menhirLib' not found
OCAMLOPT driver/Version.ml
ocamlopt.opt: unknown option '-3'.
Usage: ocamlopt <options> <files>
...
```

**ocamlfind: Package `menhirLib' not found**

menhir installed from the package, but then CompCert make suddenly needs the Lib?

I try figuring it out...

KR

**Comment by xavierleroy** [comment]
(Making sure that @fpottier knows about this discussion.)

Yes, the latest CompCert uses Menhir in "table" mode (for error reporting and what not), hence menhirLib is needed.  If you're using Ubuntu 16.04, make sure the package "libmenhir-ocaml-dev" is installed.

I don't like the `unknown option '-3'` error, though.  If it persists once you've installed the missing package, do let us know.

**Comment by bschommer** [comment]
You could also try to re-run configure. The configure scrips now takes care of finding the MenhirLib.

**Comment by ludwigschreier** [comment]
Installed libmenhir-ocaml-dev via apt and it worked. BR

**Comment by andrew-appel** [comment]
The current version of menhir still does not build on cygwin.  The workaround is to do "touch src/.versioncheck" before "make".  It would be better if this workaround were not needed.

**Comment by bschommer** [comment]
Indeed the whole versioncheck of menhir seems to me like a little bit of an overkill. @fpottier maybe a little configure script/or a SKIP_VERSION check variable would help here?

**Comment by fpottier** [comment]
Dear Andrew,

Le 13/10/2017 à 15:05, Andrew Appel a écrit :
> The current version of menhir still does not build on cygwin. The
> workaround is to do "touch src/.versioncheck" before "make". It would be
> better if this workaround were not needed.

Thanks for reporting the problem. I don't quite understand what's
special about Cygwin that causes the Makefile to fail, but I'll do
as suggested as remove the version check entirely. Most people use
opam and don't need a version check anyway.

-- 
François Pottier
francois.pottier@inria.fr
http://gallium.inria.fr/~fpottier/

**Comment by AlexanderStohr** [comment]
@fpottier - it seems like coq 8.9.1 is out and i feel like it might work for your package as well - just my 2 cent on restrictive version checking on versions that arent existing at time of release.

**Comment by fpottier** [comment]
@AlexanderStohr, the only constraint imposed by `coq-menhirlib` is that Coq should be at version 8.6 or more recent. So, I don't know what problem you are encountering?

**Comment by AlexanderStohr** [comment]
sorry if i mentioned you wrongly. my line were in facht about a CompCert requirement.
