### ISSUE TITLE
Fatal error: va_start used in non-vararg function Raised at file "pervasives.ml", line 31, characters 25-45

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#15]
The code causes a fatal error due to the use of "inline".

    $ cat foo.c
    typedef __builtin_va_list va_list;
    
    inline void foo2(const char *f, ...)
    {
        va_list args;
        __builtin_va_start((args), f);
    }
    
    void foo1(const char *str)
    {
        foo2(str, 0);
    }
    
    int main() {
        foo1("hi");
    }
    $ ccomp -fall foo.c
    Fatal error: exception Invalid_argument("Fatal error: va_start used in non-vararg function")
    Raised at file "pervasives.ml", line 31, characters 25-45
    Called from file "ia32/PrintAsm.ml", line 549, characters 4-67
    Called from file "ia32/PrintAsm.ml", line 662, characters 6-33
    Called from file "list.ml", line 73, characters 12-15
    Called from file "ia32/PrintAsm.ml", line 956, characters 2-45
    Called from file "list.ml", line 73, characters 12-15
    Called from file "ia32/PrintAsm.ml", line 1062, characters 2-50
    Called from file "driver/Driver.ml", line 162, characters 2-31
    Called from file "driver/Driver.ml", line 258, characters 6-50
    Called from file "driver/Driver.ml", line 353, characters 34-40
    Called from file "driver/Driver.ml", line 585, characters 22-70
    $ gcc -std=c99 -pedantic foo.c
    foo.c:4: warning: C99 inline functions are not supported; using GNU89
    foo.c:4: warning: to disable this warning use -fgnu89-inline or the gnu_inline function attribute
    $

**Comment by xavierleroy** [comment]
Ouch, this code is sick :-)  I hope no "real" C code tries to inline a variable-argument function.  At any rate, both GCC and Clang seem to just turn off function inlining in this case, which is a sensible thing to do.  Commit [master ce8f29b]  does the same thing: vararg functions are not eligible for inlining.  This fixes (cheaply) the current issue.
