### ISSUE TITLE
CompCert 2.7.2 for Coq 8.6?

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#157]
Are there any near-future plans for porting CompCert 2.7 and the CompCert trunk to Coq 8.6?  I would like to port VST to Coq 8.6.

**Comment by xavierleroy** [comment]
Dear Andrew: yes there are Coq 8.6 plans for the trunk and the forthcoming 2.7 release CompCert, see pull requests #150 and #156 . I take good note that you're in favor.

**Comment by andrew-appel** [comment]
Dear Xavier: 

Benoit Viguier, a PhD student at Radboud Univ. in the Netherlands, 
is visiting Princeton for 2.5 weeks now to get started on his project 
of verifying Elliptic-Curve Crypto (and other crypto) in VST. 
Step 1, he ported the CompCert trunk to Coq 8.6; 
this (mostly) repeats the work of Maxime Denes, but improves 
upon it by eliminating many warning messages. He has submitted 
this pull request to Maxime's fork of CompCert for Coq 8.6. 

As you well know, the CompCert trunk is incompatible with 
VST because you have started work on the 64-bit port, 
and some of the internal inductive data types are different. 
VST will probably not be ported to 64-bit until this summer, 
and in the meantime it would be very useful to have an "official" 
port of CompCert 2.7 to Coq 8.6. 

Therefore, Benoit proposes to port CompCert 2.7.1 to Coq 8.6, 
which he thinks will take only half a day; unless this has already 
been done by someone else. He can't submit this as a pull request, 
since it's off the main trunk. (Unless it's possible to submit a new 
branch as a pull request; he'll look into the best way to make this 
"proposed CompCert 2.7.2" available to you.) After he does this, it would be 
useful (to VST) if that version could be released as 
CompCert 2.7.2. 

Sincerely, 

Andrew

**Comment by ildyria** [comment]
Dear Xavier,

you can find [here](https://github.com/ildyria/CompCert/tree/v2.7.2) a port of the version [2.7.1](https://github.com/AbsInt/CompCert/tree/v2.7.1) taken from the tagged release. It provides Coq 8.6 compilation to the current *live* version (not the trunk), but also retro compatibility with the Coq 8.5.

Should you create a branch v2.7.2 I will be able to create a pull request to merge the changes.

**Comment by bschommer** [comment]
The release 3.0.1 uses coq 8.6.

**Comment by andrew-appel** [comment]
I don't consider this closed.  There's plenty of research that uses CompCert 2.7 that is not _nearly_ ready to port to CompCert 3.0, which has major internal changes.  This research is at Princeton (Verified Software Toolchain), at Yale (CertiKOS operating system), and probably elsewhere.  We will need to move these projects to Coq 8.6 long before we have time to port to CompCert 3.0.  

Therefore, one way or another we need a CompCert 2.7 compatible with Coq 8.6.

All we're asking is that you create a branch into which to accept Benoit's pull request!

**Comment by xavierleroy** [comment]
This issue was further discussed privately.  The port of CompCert 2.7 to Coq 8.6 done by @ildyria and mentioned above seems to fit the need.  For the time being, AbsInt and I are not keen to provide backports and further developments on older CompCert releases, but we are happy that they can exist as unofficial forks, as is the case here.
