### ISSUE TITLE
regression after fix for issue #14

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#16]
I've reverted commit 334be23a90a700f3b62806e1178603a28c6ba3bb on my end (the fix for issue #14). It seems to break my build as in this example below:

    $ ccomp -I/usr/src/lib/csu/i386 -I/usr/src/libexec/ld.so -I/usr/src/libexec/ld.so/i386 -c /usr/src/lib/csu/crt0.c
    In file included from /usr/src/lib/csu/crt0.c:39:
    /usr/src/lib/csu/boot.h:48:18: error: path.h: No such file or directory
    /usr/src/lib/csu/boot.h:49:21: error: resolve.h: No such file or directory
    /usr/src/lib/csu/boot.h:50:17: error: sod.h: No such file or directory
    /usr/src/lib/csu/boot.h:52:24: error: dl_prebind.h: No such file or directory
    Error during preprocessing.
    $
    $ ls /usr/src/libexec/ld.so/path.h
    /usr/src/libexec/ld.so/path.h

I suspect it's because the directory is called ld.so.

**Comment by xavierleroy** [comment]
The issue was here before with other file suffixes, e.g. "-Ia.c".  Fixed in commit [1278e18] by giving option rules precedence over file pattern rules.
