### ISSUE TITLE
Release tagged 3.0 seem to have the version set at 2.7.1 ?

### ISSUE THREAD

**Issue by beurdouche** [AbsInt/CompCert#164]
@xavierleroy

**Comment by xavierleroy** [comment]
Grmph.  I know I updated the version number (commit [236d8a4]) but I forgot to push this commit!  

Even though it's not completely cricket, I re-tagged release 3.0 to include this missed commit.

**Comment by xavierleroy** [comment]
I forgot: thanks a lot @beurdouche for reporting this blunder so quickly.
