### ISSUE TITLE
Error: array size is not a compile-time constant.

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#17]
The below fails:

    $ cat foo.c
    struct X { int var; };

    int main() {
            int num = sizeof(struct X);
            char* buf[num];
    }
    $ ccomp foo.c
    foo.c:5: Error: array size is not a compile-time constant.
    1 error detected.
    $ gcc -std=c99 -pedantic foo.c
    $

But this works:

    $ cat foo.c
    struct X { int var; };
    
    int main() {
            char* buf[sizeof(struct X)];
    }
    $ ccomp foo.c
    $

**Comment by xavierleroy** [comment]
"num" is not a compile-time constant expression, hence "buf[num]" is a variable-length array, which is not supported by CompCert (and probably never will).  GCC and Clang agree with this analysis:

$ gcc -pedantic -std=c90 -c foo.c
foo.c: In function ‘main’:
foo.c:5:9: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]

$ clang -pedantic -std=c90 -c foo.c
foo.c:5:18: warning: variable length arrays are a C99 feature [-Wvla-extension]
        char* buf[num];
                 ^
