### ISSUE TITLE
tmp directory recognition error

### ISSUE THREAD

**Issue by JulianXian** [AbsInt/CompCert#174]
Hello, I have successfully built compcert2.7 in cygwin environment. My Makefile.config file as follows:
PREFIX=/usr/local
BINDIR=$(PREFIX)/bin
LIBDIR=$(PREFIX)/lib/compcert
SHAREDIR=$(PREFIX)/share
OCAML_OPT_COMP=true
ARCH=powerpc
MODEL=ppc32
ABI=eabi
STRUCT_PASSING=ref-caller
STRUCT_RETURN=int1-8
SYSTEM=linux
CC=gcc
CPREPRO=gcc
CPREPRO_OPTIONS=-std=c99 -U__GNUC__ -E
CASM=gcc
CASM_OPTIONS=-c
CASMRUNTIME=gcc -c -Wa,-mregnames
CLINKER=gcc
CLINKER_OPTIONS=
LIBMATH=-lm
HAS_RUNTIME_LIB=false
HAS_STANDARD_HEADERS=false
ASM_SUPPORTS_CFI=true
CLIGHTGEN=false

 Here is my issue:
$ ccomp.exe -v -o helloworld_byccomp.o -c helloworld.c
+ gcc -std=c99 -U__GNUC__ -E -D__COMPCERT__ helloworld.c > /tmp/compcertaaec5e.i
+ gcc -c -o helloworld_byccomp.o /tmp/compcert00b387.s
gcc.exe: error: **/tmp/compcert00b387.s**: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
Error: assembler command failed with exit code 1 (use -v to see invocation)

Actually, file /tmp/compcert00b387.s exists, and  I can compile it by gcc -c **c:/cygwin**/tmp/compcert00b387.s without any problem.  It seems  that  ccomp cannot resolve the correct tmp folder. Is there any configuration parameter to control this? Thank you.

**Comment by bschommer** [comment]
Did you call ccomp.exe from cmd.exe? The problem is here that CompCert uses the system functions to generate the temporary file name, which when compiled with cygwin returns the path /tmp/compcert00b387.s and passes this to the assembler.

**Comment by JulianXian** [comment]
The  error happens in both.
**In cygwin bash**
$ PATH=/home/J/CompCert-2.7-powerpc/:/cygdrive/c/SysGCC/powerpc-eabi/bin/
$ ccomp.exe -v -o helloworld_byccomp.o -c helloworld.c
+ gcc -std=c99 -U__GNUC__ -E -D__COMPCERT__ helloworld.c > /tmp/compcertaaec5e.i
+ gcc -c -o helloworld_byccomp.o /tmp/compcert00b387.s
gcc.exe: error: /tmp/compcert00b387.s: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
Error: assembler command failed with exit code 1 (use -v to see invocation)

**In cmd.exe**
C:\SysGCC\powerpc-eabi>set PATH=C:\SysGCC\powerpc-eabi\bin;C:\SysGCC\powerpc-eab
i\libexec\gcc\powerpc-eabi\4.9.0
C:\SysGCC\powerpc-eabi>ccomp.exe -v -o helloworld_byccomp.o -c helloworld.c
+ gcc -std=c99 -U__GNUC__ -E -D__COMPCERT__ helloworld.c > /tmp/compcert428580.i
+ gcc -c -o helloworld_byccomp.o /tmp/compcert0bc606.s
gcc.exe: error: /tmp/compcert0bc606.s: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
Error: assembler command failed with exit code 1 (use -v to see invocation)

I prefer using the latter. Then how to add the wrapper?  To modify driveraux.ml or to do something else?

**Comment by bschommer** [comment]
Could it be the case that the gcc you are using is not compiled with cygwin? In that case the easiest way is to write a little cygwin script to translate all paths to windows path using `cygpath -wa`.

**Comment by bschommer** [comment]
I think this issue is due to the fact that cygwin binaries and non-cygwin binaries are mixed, dues resulting in mixed up paths. This [blogpost](https://noamlewis.wordpress.com/2011/03/22/how-to-run-any-windows-program-from-cygwin-still-using-cygwin-style-path/l) shows how to work around this from within cygwin.

**Comment by JulianXian** [comment]
Thank you for your help
