### ISSUE TITLE
"-dall" option lacks "-dltl"

### ISSUE THREAD

**Issue by alxest** [AbsInt/CompCert#176]
https://github.com/AbsInt/CompCert/blob/master/driver/Driver.ml#L370
It seems "-dall" option turns all the tracking options, except "-dltl".
Is this intended? I guess this could be a mistake, so I leave it as an issue.
Thanks a lot.

**Comment by bschommer** [comment]
Thanks for the spotted mistake. Should be fixed by de24549f572deb6519be2216ef364b7c80bfdece.
