### ISSUE TITLE
Syntax error while gcc doesn't flinch

### ISSUE THREAD

**Issue by atrieu** [AbsInt/CompCert#178]
Hello,

I get a syntax error with the following program (absolutely not minimal, apologies)

````
#include "ftfp.h"
#include "internal.h"
#include "base.h"

int main(void) {
  int x = 0;
  int y = 0;
  FIX_EQ(x, y);
  return 0;
}
````
where `base.h` contains the following code
````
#ifndef base_h
#define base_h

#include <stdint.h>
#include <inttypes.h>

typedef uint64_t fixed;

#define FIX_PRINT_BUFFER_SIZE 43

#define FIX_PRINTF_HEX "%016"PRIx64
#define FIX_PRINTF_DEC "%"PRId64

#define FIX_FLAG_BITS 2
#define FIX_FRAC_BITS 30
#define FIX_INT_BITS  32
#define FIX_BITS (8*sizeof(fixed))

#define FIX_INTERN_FRAC_BITS 60
#define FIX_INTERN_INT_BITS 4

static const fixed fix_pi = 0x00000003243f6a88;
static const fixed fix_tau = 0x00000006487ed510;
static const fixed fix_e = 0x00000002b7e15164;

#define FIX_PI fix_pi
#define FIX_TAU fix_tau
#define FIX_E fix_e

#endif
````
and `ftfp.h` and `internal.h` are taken from the [libfixedtimefixedpoint](https://github.com/kmowery/libfixedtimefixedpoint)

I get the following error `./internal.h:497:21: syntax error after '(' and before '{'.` with both CompCert 2.7.1 and current master git branch versions while gcc doesn't complain at all.

Thanks

**Comment by jhjourdan** [comment]
The definition of `SIGN_EXTEND_64` in `internal.h` uses an extension of the C language supported by Gcc, but not required by the C standard, nor supported by the parser of Compcert. This extension is called "statement expressions":

https://gcc.gnu.org/onlinedocs/gcc-4.8.2/gcc/Statement-Exprs.html#Statement-Exprs

**Comment by jhjourdan** [comment]
It should be possible to redefine SIGN_EXTEND_64 using a function (that should be inlined) instead of a macro, though.

**Comment by xavierleroy** [comment]
Yes, GCC and Clang handle a superset of standard C, and no, CompCert doesn't handle most of the GCC/Clang extensions to C.  Write standard C instead.

**Comment by atrieu** [comment]
Oh okay, sorry for the noise and thanks for the answer
