### ISSUE TITLE
bug in ExportClight.ml

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#179]
In CompCert 2.7.1 and CompCert 3.0, there is a bug in the "clightgen" utility, in exportclight/ExportClight.ml.   The "switch" statement is printed into Coq code that does not type-check.  The buggy code prints out "LScase" instead of "LScons", and prints "" instead of "LSnil".

The wrong code is as follows:

and lblstmts p = function
  | LSnil ->
      ()
  | LScons(lbl, s, ls) ->
      fprintf p "@[<hv 2>(LScase %a@ %a@ %a)@]"
              (print_option coqint) lbl stmt s lblstmts ls

The correct code is:

and lblstmts p = function
  | LSnil ->
      (fprintf p "LSnil")
  | LScons(lbl, s, ls) ->
      fprintf p "@[<hv 2>(LScons %a@ %a@ %a)@]"
              (print_option coqZ) lbl stmt s lblstmts ls

with the function,

let coqZ p n =
  let n = camlint_of_coqint n in
  if n >= 0l
  then fprintf p "%ld" n
  else fprintf p "(%ld)" n

I apologize for not packaging this as a pull request.

It would be helpful if you could update the CompCert 2.7.1 distribution to fix this bug, so that users of VST can use a standard CompCert distribution rather than a nonstandard patched one.

**Comment by m-schmidt** [comment]
I packaged it as a PR to the current trunk (see #180).

**Comment by xavierleroy** [comment]
Fixed on master by commit 2fbdb0c .  

Currently, AbsInt and I have no policy for backporting fixes to older releases.  I believe the commit above applies cleanly to 2.7.  Perhaps @ildyria could apply it to the unofficial 2.7.2 version at https://github.com/ildyria/CompCert/tree/v2.7.2 .
