### ISSUE TITLE
Compilation fails for building RISC-V

### ISSUE THREAD

**Issue by joonwonc** [AbsInt/CompCert#181]
Hello,

I've just tried to pull the master branch and to compile the code with the RISC-V 32-bit configuration, but it looks like the current code doesn't compile. Here are some information about the compile error:

- The Coq version I'm using:
> The Coq Proof Assistant, version 8.6 (May 2017)
> compiled on May 3 2017 23:44:31 with OCaml 4.02.3

- Compile error messages:
> File "./backend/Allocproof.v", line 2471, characters 2-38:
> Error: Proof is not complete.
> make[1]: *** [backend/Allocproof.vo] Error 1

I'm not sure this is related to the configuration I made, but here are the configuration arguments:
> ./configure -toolprefix riscv32-unknown-elf- rv32-linux

Thanks!

**Comment by m-schmidt** [comment]
Thanks for reporting this. I can reproduce the problem and we will have a look at it.

Please note, that there is no official release of CompCert with support for RiscV yet.

**Comment by xavierleroy** [comment]
Fixed by commit [master 054d358].  

Indeed, the RISC-V port is still in beta-test, but keeping this in mind, feedback is very welcome!

**Comment by bschommer** [comment]
Compilation now works. Alas we can close this bug.
