### ISSUE TITLE
towards running SPEC CPU 2017

### ISSUE THREAD

**Issue by regehr** [AbsInt/CompCert#187]
so far I'm only looking at the subset of the "integer speed" subset of this benchmark that happens to be written in C. this leaves five benchmark programs that CompCert might be able to run:

  600.perlbench_s 602.gcc_s 605.mcf_s 625.x264_s 657.xz_s

on an x86-64 machine running Ubuntu 16.04, "ccomp -fall -O" is able to compile two of these:

   605.mcf_s 625.x264_s

the resulting executables produce the expected outputs for the "ref" inputs.

the other three programs appear to contain constructs not yet supported by CompCert. I'm using a CompCert recently build from the master branch. I'll add more details later once I've looked into them.

**Comment by xavierleroy** [comment]
Any news on this issue?

**Comment by xavierleroy** [comment]
This issue has been inactive for way too long, so pardon me for closing it.  I'm still interested in SPEC benchmark results but have no intention to purchase and run SPEC benchmarks myself.
