### ISSUE TITLE
Unsupported feature: ill-formed 'switch' statement

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#19]
gcc is able to compile an empty switch statement but compcert does not seem to be able to.

    $ cat foo.c
    int main() {
        int i = 0;
        switch(i) {
        }
    }
    $ cc -std=c89 -pedantic foo.c
    $ cc -std=c99 -pedantic foo.c
    $ ccomp -fall foo.c
    foo.c:3: Unsupported feature: ill-formed 'switch' statement
    $

**Comment by xavierleroy** [comment]
Indeed there is a check for empty "switch" statements,  but it serves no purpose, as the formal semantics for CompCert C defines the behavior of empty "switch" (as doing nothing).  Commit [master 05f1ccc] just removes the check.
