### ISSUE TITLE
wrongly typed debug info for 64 bits 

### ISSUE THREAD

**Issue by fajb** [AbsInt/CompCert#190]
Hello,

The SimplLocals pass inserts debug annotations that are not well-typed for 64 bits architectures.
For instance, at the Cminor level, I can get 
"foo"() : void
{
  stack 4;
  builtin debug5 "x"(&0) : int -> void;
}
&0 is an address and should therefore have type long.

I think the guilty piece of code is SimplLocals.Sdebug_var where AST.Tint should be AST.Tptr.

**Comment by xavierleroy** [comment]
Well spotted, thank you.  I'll fix this soon.  

Debugger support has received less attention for x86_64 than for other, older, 32-bit platforms, so there might be other issues of this kind.

**Comment by xavierleroy** [comment]
Fixed by commit [master 0d783f1]
