### ISSUE TITLE
Coq 8.6.1 support

### ISSUE THREAD

**Issue by vzaliva** [AbsInt/CompCert#193]
Please support Coq 8.6.1. Currently, CompCert does not compile under 8.6.1 as it fails version check in configure script.

**Comment by m-schmidt** [comment]
The current trunk version should support Coq 8.6.1.

**Comment by m-schmidt** [comment]
I consider this closed. If there are questions feel free to reopen.

**Comment by vzaliva** [comment]
No questions but minor official release would be nice. Currently, coq-compcert OPAM package is not available via opam and downloads page offers compcert version which is not compatible with latest coq version.

**Comment by m-schmidt** [comment]
I forgot to mention this: yes, there will be a new release within the next few weeks.

**Comment by m-schmidt** [comment]
FYI: there is now a CompCert 3.1 release with official support of Coq 8.6.1.
