### ISSUE TITLE
support 64-bit on openbsd

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#194]
Possible to add support for OpenBSD/amd64 to the configure script? i'm happy to send my local patch over but the configure file is not BSD licensed. I've run some (very) basic tests my end and things seem to work.

**Comment by xavierleroy** [comment]
Yes, of course, just send us the lines to add to the configure script.  I expect the diff to be small, in which case there is no copyright attached and no licensing issues with putting it into our configure script.

**Comment by xavierleroy** [comment]
@didickman thanks for sending the diff, it's committed in 81bcef3.
