### ISSUE TITLE
Merge clightgen-norm into master

### ISSUE THREAD

**Issue by lennartberinger** [AbsInt/CompCert#195]
The clightgen tool in clightgen-norm branch adds the option -normalize, which isolates certain
expressions from commands, in support of VST (and perhaps other present or future program analyses).
It's in Ocaml and unverified, but it would be great to have it merged to master, so that future evolutions to master don't need to be individually merged into or duplicated in clightgen-norm.

**Comment by andrew-appel** [comment]
This merge request is quite important to the Verified Software Toolchain project: it permits VST to be applied to C programs that have memory accesses in subexpressions (not just in top-level assignment expressions).

**Comment by xavierleroy** [comment]
The clightgen-norm branch was merged on master on Jun 12th.  Thanks for the reminder to delete the branch.
