### ISSUE TITLE
Clightgen produces output whose processing doesn't terminate, in the proof of prog_comp_env_eq

### ISSUE THREAD

**Issue by lennartberinger** [AbsInt/CompCert#196]
An example 
[digests_v.txt](https://github.com/AbsInt/CompCert/files/1215143/digests_v.txt)
(extension txt is added to make github accept the attachment, really, it's digests.v)
 is attached, and was generated from a lightly edited version of https://boringssl.googlesource.com/boringssl/+/2357/crypto/digest/digests.c.
The issue is that the refl_equal in the penultimate line of the file does not terminate.
(The issue has also been observed on other files of roughly the same size)

**Comment by andrew-appel** [comment]
Here's a solution to this problem.  I request that AbsInt implement this solution, if you can't find a better one.  (This solution works for CompCert 2.7.2, but it should work for CompCert 3.0 with little or no modification.)

Replace the next-to-last line of digests.v (or any file that is the output of clightgen) with:

prog_comp_env_eq := ltac:(prove_composites_ok)

That is, change "refl_equal _" to "ltac:(prove_composites_ok)"

Put the following lines into Clightdefs.v:


Definition not_error {A} (x: Errors.res A) : Prop :=
  match x with Errors.Error _ => False | _ => True end.

Lemma not_error_composite_env: forall x,
  not_error (build_composite_env x) ->
 build_composite_env x = Errors.OK (make_composite_env x).
Proof.
 intros.
 unfold make_composite_env.
 destruct (build_composite_env x); auto.
 simpl in H. contradiction H.
Qed.

Lemma not_error_add_composite: 
  forall env id su ms a defs, 
    Maps.PTree.get id env = None ->
    complete_members env ms = true -> 
    Coqlib.align (sizeof_composite env su ms) (align_attr a (alignof_composite env ms)) >= 0 ->
     not_error (add_composite_definitions 
                (Maps.PTree.set id 
                  {| co_su := su; co_members := ms; co_attr := a; 
                     co_sizeof := Coqlib.align (sizeof_composite env su ms)
                                         (align_attr a (alignof_composite env ms));
                     co_alignof := align_attr a (alignof_composite env ms);
                     co_rank := rank_members env ms;
                     co_sizeof_pos := Ctypes.composite_of_def_obligation_1 env su ms a;
                     co_alignof_two_p := Ctypes.composite_of_def_obligation_2 env ms a;
                     co_sizeof_alignof := Ctypes.composite_of_def_obligation_3 env su ms a |}
                  env) defs) ->
    not_error (add_composite_definitions env (Composite id su ms a :: defs)).
Proof.
intros.
unfold add_composite_definitions; fold add_composite_definitions.
unfold composite_of_def.
rewrite H.
rewrite H0.
unfold Errors.bind.
apply H2.
Qed.

Ltac check_add_composite :=
simple apply not_error_add_composite;
  [reflexivity | reflexivity | compute; intro Hx; inversion Hx | ];
match goal with |- 
  not_error (add_composite_definitions (Maps.PTree.set _ 
         {|  co_members := ?M; co_sizeof := ?S1; co_alignof := ?S2; co_rank := ?S3 |} _) _)  =>
  let s := fresh "s" in
  set (s := S1); compute in s; subst s;
  set (s := S2); compute in s; subst s;
  set (s := S3); compute in s; subst s;
  let m := fresh "m" in set (m:=M)
end;
 simpl Maps.PTree.set;
match goal with |- 
  not_error (add_composite_definitions ?E _) =>
    let e := fresh "e" in set (e:=E)
end.

Ltac prove_composites_ok :=
  apply not_error_composite_env;
  unfold composites, build_composite_env, Maps.PTree.empty;
  repeat check_add_composite; apply Logic.I.

**Comment by m-schmidt** [comment]
Thanks, we will discuss this with Xavier later this month.

**Comment by xavierleroy** [comment]
Thanks for the repro case.  I confirm that, empirically, the `(refl_equal _)` proof takes time exponential in the number of struct/union definitions...  Both computing the two environments to compare and actually testing them for equality take a lot of time each.  I'm not sure where the exponential factor comes from, although I can see a quadratic factor.  At any rate, I see no way to control Coq's evaluation strategy so that this case of computational reflection works efficiently.

Commit [master ab6d5e9] implements a fix that is a simplification of @andrew-appel 's: `not_error (build_composite_env x)` can be checked efficiently by computation (just by giving `Logic.I` as the proof term).  From there it's all once-and-for-all proof, in the style of @andrew-appel 's `not_error_composite_env` lemma.  

I think this commit applies to CompCert 2.7.1 as well.  

Let us know if it works on your examples.

**Comment by xavierleroy** [comment]
The new implementation is now in release 3.1.  If similar issues still occur, please reopen this problem report.
