### ISSUE TITLE
Printing of Cminor Sswitch

### ISSUE THREAD

**Issue by fajb** [AbsInt/CompCert#201]
The printer and (obsolete) parser for Cminor do not agree for switch cases.
Anyway, I think the printer is wrong : the case should be printed as either a Int32 or Int64.

A possible fix is:
  | Sswitch(long, e, cases, dfl) ->
     let print_case_idx p z =
       if long then fprintf p "%LdLL" (Z.to_int64 z)
       else fprintf p "%ld" (Z.to_int32 z) in

     fprintf p "@[<v 2>switch%s (%a) {"
        (if long then "l" else "") print_expr e;
      List.iter
        (fun (n, x) ->
           fprintf p "@ case %a: exit %d;"
                   print_case_idx n
                   (Nat.to_int x))
        cases;
      fprintf p "@ default: exit %d;\n" (Nat.to_int dfl);
      fprintf p "@;<0 -2>}@]"

**Comment by bschommer** [comment]
Fixed by 115825af0f765bf26270f9b9a2c550eddd76d7bd .
