### ISSUE TITLE
Version 3.1 reports as version 3.0.1

### ISSUE THREAD

**Issue by Zimmi48** [AbsInt/CompCert#205]
```
$ ccomp --version
The CompCert C verified compiler, version 3.0.1
```

This is likely due to this line not having been updated:
https://github.com/AbsInt/CompCert/blob/993a19e07ebf6e178e23fe6c02a2f25736835c1d/VERSION#L1

**Comment by m-schmidt** [comment]
Thanks, we will fix this.

**Comment by m-schmidt** [comment]
Done.

**Comment by xavierleroy** [comment]
Thanks @Zimmi48 for the report and @m-schmidt  for the fix.  This isn't the first time that the VERSION file is wrong...

**Comment by Zimmi48** [comment]
I suggest either scripting or simply documenting the release process in the form of a TODO list. We don't have one yet for Coq but I hope we will soon.
