### ISSUE TITLE
decode_val, Fragment, Mfloat32: int/float conversions incomplete

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#207]
Consider this C program (where sizeof(int)=sizeof(float)=4):

union {float f; unsigned int i; } u;

int test (union u *p) {
  if (p->i <> 0) return 1;
  return (p->f == 0.0);
}

I claim that this function **must** return 1, and I claim that it is intended that this fact be provable regarding CompCert C.  It is for that reason that the encoding of IEEE floating point as sequences of "memval" is written so explicitly.

Such int/float unions are used in some real C programs to manipulate floating point values (such as to compute fabs), and that provides motivation to make this provable.

But, in fact, I believe this program cannot be proved correct.  
Before I explain why, let me remark that proof would need both of these facts to be true:

Hypothesis float32_to_int32:    (* this one is true *)
  forall (bl: list memval) (x: float32), length bl = 4 ->  
  decode_val Mfloat32 bl = Vsingle x -> decode_val Mint32 bl = Vint (Float32.to_bits x).

Hypothesis int32_to_float32:  (* this one is false *)
  forall (bl: list memval) (x: float32), length bl = 4 ->  
  decode_val Mint32 bl = Vint (Float32.to_bits x) -> decode_val Mfloat32 bl = Vsingle x.

In fact, the second hypothesis is false, as I will demonstrate at the end of this message by proving its negation.  

So, why is the program unprovable, and why is the second hypothesis false? 
If we assume the contents of memory at address p is a 4-byte sequence of Byte memvals, then in fact the program is provable and both hypotheses would be true.   

But what if the contents of memory at address p is a 4-byte sequence of Fragments?  In that case, the Fragments could reassemble into a Vint or a Vfloat, but they will not be considered equal, even if their Byte representation was the same.

(In the remainder of this message, I'm using CompCert 2.7.2, but I've inspected the current CompCert trunk and it seems to be the same there.)

Look at the definition of Memdata.decode_val:

Definition decode_val (chunk: memory_chunk) (vl: list memval) : val :=
  match proj_bytes vl with
  | Some bl => . . .
  | None =>
      match chunk with
      | Mint32 | Many32 => Val.load_result chunk (proj_value Q32 vl)
      | Many64 => Val.load_result chunk (proj_value Q64 vl)
      | _ => Vundef
      end
  end.

In the case where "bl" is a sequence of fragments, proj_bytes returns None, and the inner pattern-match uses Val.load_result to reassemble the value **if the chunk is Mint32 but not if the chunk is Mfloat32**.  It does not help to add Mfloat32 to the first clause of the match, that just makes **both** hypotheses false instead of just one of them.  Instead, the problem is:  

"Fragment v q n" should be considered meaningful **only** if v is a Vptr value.  I suspect that no CompCert operation (including externals such as memcpy) will ever produce a memory containing (Fragment (Vint _) _ _), if the memory did not already contain such a value.

I propose that it should be an invariant of the CompCert execution that the first argument of Fragment must be a Vptr or Vundef.  I propose that one simple way to achieve this is to modify Memdata.check_value to check that v is Vptr or Vundef;  that is, CompCert will be stuck if it tries to load a memval of the form (Fragment (Vint _) _ _).  However, I am not 100% sure that this is the right solution.

An alternate solution is to leave the CompCert semantics the way it is, and I'll assume this stricter operational semantics for the proof of my Verifiable C program logic.  Then I can still achieve my desired soundness result, by proving a refinement relation between the two semantics.

(* Proofs of the promised hypothesis and negated hypothesis, w.r.t. CompCert 2.7.2 *)

`Require Import Memdata Floats Values AST Integers.
Require Import ZArith.
Require Import List. Import ListNotations.

Lemma decode_float32_int32:
  forall (bl: list memval) (x: float32),
 size_chunk Mfloat32 = Z.of_nat (Datatypes.length bl) ->
 decode_val Mfloat32 bl = Vsingle x ->
 decode_val Mint32 bl = Vint (Float32.to_bits x).
Proof.
intros.
unfold decode_val,decode_int,rev_if_be in *.
destruct (proj_bytes bl) eqn:?H.
inversion H0; clear H0; subst.
rewrite Float32.to_of_bits. auto.
inversion H0.
Qed.

Lemma NOT_decode_int32_float32:
 ~ (forall (bl: list memval) (x: float32),
     size_chunk Mfloat32 = Z.of_nat (Datatypes.length bl) ->
     decode_val Mint32 bl = Vint (Float32.to_bits x) ->
     decode_val Mfloat32 bl = Vsingle x).
Proof.
+
intro.
set (x := Float32.zero). (* nothing special about zero, any value would do *)
set (i := Float32.to_bits x).
set (bl := [Fragment (Vint i) Q32 3; Fragment (Vint i) Q32 2; Fragment (Vint i) Q32 1; Fragment (Vint i) Q32 0]).
specialize (H bl x).
specialize (H (eq_refl _)).
assert (decode_val Mint32 bl = Vint (Float32.to_bits x)).
unfold decode_val, bl.
simpl.
destruct (Val.eq (Vint i) (Vint i)); [ | congruence].
destruct (quantity_eq Q32 Q32); [ | congruence].
simpl.
reflexivity.
specialize (H H0).
clear - H. subst bl i.
unfold decode_val in H.
simpl in H. inversion H.
Qed.
`

**Comment by xavierleroy** [comment]
Dear @andrew-appel, 

I'm not sure why you're using this issue tracker rather than e-mailing me.  At any rate, the extension of `Fragment` memvals to hold arbitrary values instead of just pointers was discussed with you and others in an e-mail exchange starting Sun Jun 15 2014.  It is necessary for the Spilling pass to work properly.  
When saving and restoring callee-save registers, the  actual types for the data contained in these registers at function entry is not known, hence it doesn't work to save and reload, say, with a `Mfloat64` chunk, because the value may be a `Vsingle` and will not read back correctly.  So:

> "Fragment v q n" should be considered meaningful only if v is a Vptr value.

That's not enough for the spilling pass.

> I suspect that no CompCert operation (including externals such as memcpy) will ever produce a memory containing (Fragment (Vint _) _ _), if the memory did not already contain such a value.

`Mem.store` with a `Many32` or `Many64` chunk and a `Vint` value will produce this.

**Comment by andrew-appel** [comment]
I'm not always sure which issues are best for the issue tracker and which I should ask you directly in e-mail.

In any case, it appears that Many32 and Many64 are not used by any of the CompCert operational semantics of any intermediate language before Asm.v (the various target architectures).  So a weak form of my conjecture may still hold.  I'll take the rest of the discussion offline.
