### ISSUE TITLE
C99 for-loop defined variable gets incorrect scope

### ISSUE THREAD

**Issue by MarcelAtSolidSands** [AbsInt/CompCert#211]
We found a run-time error with SuperTest for the program below. The program should print 100 for the value of 'press', but when compiled with CompCert 3.1 on an x86 Apple Mac, it prints 3. It looks like CompCert is confused about the scopes of the two variables called 'press'.

===========================================

#include <stdio.h>

int press = 100;
int valve = 0;

int main (void) {
    for (int press = 0; press < 3; press++) {
        valve++;
    }
    printf ("Value of 'press' should be 100, is: %d\n", press);
    return valve - 3;
}

**Comment by bschommer** [comment]
Should be fixed by 6753e8f33cd4b26dbb256ae4886f11d60eb0e370
