### ISSUE TITLE
Bug in clightgen:  Cannot infer the implicit parameter V of Gfun

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#215]
Clightgen is broken (in the current master branch), and the fix is easy.

The output of clightgen includes:

Definition global_definitions :=
((___builtin_bswap,
   Gfun(External (EF_builtin "__builtin_bswap"
                   (mksignature (AST.Tint :: nil) (Some AST.Tint) cc_default))
     (Tcons tuint Tnil) tuint cc_default)) ::
  . . . (* et cetera *)

Coq produces this error message:

Cannot infer the implicit parameter V of Gfun whose type is "Type".

The solution is for clightgen to produce:

Definition global_definitions : list (ident * globdef fundef type) :=
((___builtin_bswap,
   Gfun(External (EF_builtin "__builtin_bswap"
                   (mksignature (AST.Tint :: nil) (Some AST.Tint) cc_default))
     (Tcons tuint Tnil) tuint cc_default)) ::
  . . . (* et cetera *)

This can be fixed by a very simple change to ExportClight.ml:

Line 552:
  fprintf p "Definition global_definitions : list (ident * globdef fundef type) :=@ ";

**Comment by xavierleroy** [comment]
Thanks for the report.  It would also fail to infer the F parameter if the source file contains no functions!  Fixed by @bschommer in commit 2b59816 . Will be in release 3.2.
