### ISSUE TITLE
Bug in clightgen: Int_addrof uses Int.repr instead of Ptrofs.repr

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#216]
Consider the following C code:

struct list {unsigned head; struct list *tail;};
struct list three[] = {  {1, three+1}, {2, three+2}, {3, NULL} };

Clightgen produces:

Definition v_three := {|
  gvar_info := (tarray (Tstruct _list noattr) 3);
  gvar_init := (Init_int32 (Int.repr 1) :: Init_addrof _three (Int.repr 8) ::
                Init_int32 (Int.repr 2) ::
                Init_addrof _three (Int.repr 16) ::
                Init_int32 (Int.repr 3) :: Init_int32 (Int.repr 0) :: nil);
  gvar_readonly := false;
  gvar_volatile := false
|}.

Coq says:   The term "Int.repr 8" has type "int" while it is expected to have type "ptrofs".

Clightgen should produce:

Definition v_three := {|
  gvar_info := (tarray (Tstruct _list noattr) 3);
  gvar_init := (Init_int32 (Int.repr 1) :: Init_addrof _three (Ptrofs.repr 8) ::
                Init_int32 (Int.repr 2) ::
                Init_addrof _three (Ptrofs.repr 16) ::
                Init_int32 (Int.repr 3) :: Init_int32 (Int.repr 0) :: nil);
  gvar_readonly := false;
  gvar_volatile := false
|}.

**Comment by xavierleroy** [comment]
Thanks for the report.  Fixed by @bschommer in commit ce7013f.  Will be in release 3.2.
