### ISSUE TITLE
clightgen -version

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#218]
$ ./clightgen --version
, Tag: : ert Clight generator, 3.2

$ ./clightgen -version
, Tag: : ert Clight generator, 3.2

$ ./clightgen --help
. . . doesn't even mention the --version flag ...

**Comment by bschommer** [comment]
Is fixed by commit 4a2fed6f5e11799fabcb6fb38153e09af6f10d64 . Also some of the other command line switches for the frontend are now available in clightgen.
