### ISSUE TITLE
Install does not install .vo files

### ISSUE THREAD

**Issue by ildyria** [AbsInt/CompCert#227]
.vo files are used with VST.

https://github.com/coq/opam-coq-archive/pull/292 changed the path for the libs but the `makefile` does not take care of the installation of the `.vo`. It would be a nice addition to help the development with VST.

**Comment by lastland** [comment]
Hi, what do CompCert people think about this PR? If accepted, it would be very useful for people who want to install VST via opam.

**Comment by m-schmidt** [comment]
Thanks for the PR, but we are currently busy with other things. Please be patient a little longer.
