### ISSUE TITLE
configure should remove Makefile.config if given invalid arguments

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#244]
Please have the configure script remove Makefile.config before building a new one.  I just wasted an hour because (1) I already had a Makefile.config, then (2) I did ` ./configure x86_64-cygwin` , which is not currently a permitted option.  So yes, ./configure produced an error message, but I missed it because "make" seemed to work just fine.

**Comment by xavierleroy** [comment]
It makes a lot of sense.  See pull request #251 for an implementation + some other improvements to configure's error handling.
