### ISSUE TITLE
type signature of builtin_ais_annot does not match

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#247]
In the master branch of CompCert pulled yesterday from github, commit a40a2797d80d510bcd36bb72cf3eafba4cee1bd5  

Using clightgen built with x86_64-linux, the output .v file contains this:
```
Definition global_definitions : list (ident * globdef fundef type) :=
((___builtin_ais_annot,
   Gfun(External (EF_builtin "__builtin_ais_annot"
                   (mksignature (AST.Tint :: nil) None
                     {|cc_vararg:=true; cc_unproto:=false; cc_structret:=false|}))
     (Tcons (tptr tschar) Tnil) tvoid
     {|cc_vararg:=true; cc_unproto:=false; cc_structret:=false|})) ::

```

Notice that the type `AST.Tint` does not match the type` (tptr tschar)`.  This appears to be a bug.

**Comment by xavierleroy** [comment]
Sorry if I sound like a broken record, but I can't reproduce.
```
$ git checkout a40a279
$ ./configure -clightgen x86_64-linux
$ make -j8
$ cd test/clightgen
$ make integr.v
$ grep -A 7 global_definitions integr.v
Definition global_definitions : list (ident * globdef fundef type) :=
((___stringlit_1, Gvar v___stringlit_1) ::
 (___builtin_ais_annot,
   Gfun(External (EF_builtin "__builtin_ais_annot"
                   (mksignature (AST.Tlong :: nil) None
                     {|cc_vararg:=true; cc_unproto:=false; cc_structret:=false|}))
     (Tcons (tptr tschar) Tnil) tvoid
     {|cc_vararg:=true; cc_unproto:=false; cc_structret:=false|})) ::
--
```
It looks like the output.v file you're looking at was generated by CompCert built for a 32-bit platform.

**Comment by andrew-appel** [comment]
I had a "clightgen" that produced, 

```
Module Info.
  Definition version := "3.3"%string.
  Definition build_number := ""%string.
  Definition build_tag := ""%string.
  Definition arch := "x86"%string.
  Definition model := "64"%string.
  Definition abi := "standard"%string.
  Definition bitsize := 32.
  Definition big_endian := false.
  Definition source_file := "progs/foo.c"%string.
  Definition normalized := true.
End Info.
```

Notice that `bitsize `does not match `model`.

I obtained this clightgen by cleaning out a 32-bit compcert build, doing "./configure x86_64-linux -clightgen", and the doing a new build.   I thought I had "cleaned out" by doing "make clean", thus my issue report #249, but apparently I must have just done "rm */*.vo */*/*.vo", which didn't remove the .o files in exportclight.  The result was a hybrid "chimera" build that was 64-bit in the Coq files but partly 32-bit in the exportclight directory.

So, mostly my fault.  However, one might imagine that the dependency information in the Makefile, if more accurate and complete, would have rebuilt the appropriate parts of exportclight/*.o.

So therefore, I withdraw this bug report.

**Comment by xavierleroy** [comment]
Thanks for the explanation of the mysterious failure.

It is true that the existing dependencies are too weak to track reconfiguration and change of target platform.  Maybe someone will eventually give it a try.  In the meantime `make clean` is your friend!
