### ISSUE TITLE
cparser/Parser.v should be made readonly

### ISSUE THREAD

**Issue by JasonGross** [AbsInt/CompCert#248]
The Makefile issues `chmod a-w` for `.v` files generated from `.vp` files, but not for `cparser/Parser.v` generated from `cparser/Parser.vy`.  This caused me a bit of confusion when I had code that built locally but not on the CI, because I didn't notice that `cparser/Parser.v` was autogenerated.

**Comment by xavierleroy** [comment]
Dear Jason: you're right, it makes sense to protect `cparser/Parser.v` as well.  Done in commit 9083177.

I hope  this will not cause problems with Cygwin (see https://caml.inria.fr/mantis/view.php?id=6319 for a weird chmod issue we had with OCaml);  CI will tell soon.

**Comment by xavierleroy** [comment]
CI is fine, no Cygwin issues.
