### ISSUE TITLE
"Make clean" does not clean up the exportclight directory

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#249]
"make clean" should remove the .o files (and other generated files) in exportlight/  but it does not.

**Comment by xavierleroy** [comment]
I'm not able to reproduce the problem with the CompCert master.
```
$ configure -clightgen x86_64-linux
$ make -j8
$ ls exportclight/
Clightdefs.v   Clightgen.cmx   Clightnorm.cmt  ExportClight.cmi  ExportClight.o
Clightdefs.vo  Clightgen.ml    Clightnorm.cmx  ExportClight.cmt  README.md
Clightgen.cmi  Clightgen.o     Clightnorm.ml   ExportClight.cmx
Clightgen.cmt  Clightnorm.cmi  Clightnorm.o    ExportClight.ml
$ make clean
$ ls exportclight/
Clightdefs.v  Clightgen.ml  Clightnorm.ml  ExportClight.ml  README.md
```
What is the problem that you're observing?

**Comment by andrew-appel** [comment]
I was wrong; "make clean" does remove the appropriate files in exportclight/.
See my comment beginning 'I had a "clightgen" that produced,' in issue #247 for an explanation of how I became confused.
