### ISSUE TITLE
Small bug in the Makefile?

### ISSUE THREAD

**Issue by planar** [AbsInt/CompCert#25]
Line 185 of the Makefile tries to remove `doc/glob/$(*F).glob` but it always fails because `doc/glob/` does not exist. And indeed line 187 creates file `doc/$(*F).glob`, without the `glob/` part.

**Comment by bschommer** [comment]
Changed the rm to remove the files doc/$(*F).glob in commit fd204b20e4ac3c41e1826f99344023d294a834c0 .
