### ISSUE TITLE
Please make your project compile with -w "+compatibility-notation"

### ISSUE THREAD

**Issue by Zimmi48** [AbsInt/CompCert#253]
Please make your project compile with `-w "+compatibility-notation"` to prepare for the Coq 8.9 release. We would appreciate if this could be done ASAP. If you have trouble doing so, please raise your concern at coq/coq#8383.

**Comment by xavierleroy** [comment]
I really need to talk with the Coq 8.9 release manager.  Please have him contact me directlly.

**Comment by xavierleroy** [comment]
Especially since all the "compatibility-notation" warnings in CompCert come from Flocq, the library he maintains :-)  Note that we CompCert folks make no changes to our copy of Flocq unless the change is first made upstream in Flocq.

**Comment by Zimmi48** [comment]
Hi @xavierleroy, I don't better access to @silene than you have. And sorry for not noticing that the problem came from Flocq, I already opened an issue at https://gitlab.inria.fr/flocq/flocq/issues/4. I will close this one then.

Regarding the question of whether this will actually be necessary for the 8.9, I think nothing is decided yet. I'll post a more detailed comment at coq/coq#8383 explaining all the issues at stake but in the end, if users want to protest this change, they can. Do not hesitate to raise any concern you may have.

Regarding the way you manage the dependency on Flocq, there is also an interesting discussion to have. Among the projects that we have in our CI, we have at least three ways of managing dependencies:
- those - for instance the Iris team in MPI - that assume that the dependencies will be installed prior to compiling the project (and document it, and put it in their OPAM file);
- those - for instance most of the MIT projects - who use submodules to manage them and as soon as they are initialized, their Makefile will take care of building them;
- those - CompCert with Flocq and VST with CompCert - who copy-paste the code of their dependencies in their own repositories.

For sure it would be easier for us to manage if there was only one way. I don't have yet any great solution to propose though, otherwise I would be more adamant in imposing it.
