### ISSUE TITLE
Running 'make clightgen' fails

### ISSUE THREAD

**Issue by odgalvin** [AbsInt/CompCert#260]
I can't seem to run 'make clightgen' to just build clightgen rather than all of CompCert, for example for use with the Verified Software Toolchain project.
I get this output:
```
COQC Axioms.v
coqc: Axioms.v: no such file or directory
make: *** [Makefile:197: Axioms.vo] Error 1
```

I also got the same output for some other make targets. Axioms.v is in /lib, I guess it's not looking in the right directory.
Thanks

**Comment by atrieu** [comment]
Have you tried using `./configure` beforehand ?
Alternatively, you may also want to try `make depend` too.

**Comment by bschommer** [comment]
Indeed you need to run `./configure` first and additionally call `make depend` before calling `make clightgen`.

**Comment by odgalvin** [comment]
I had run `./configure`, it was `make depend` that did the trick. Could be worth adding to the docs. Thanks!
