### ISSUE TITLE
NULL should be defined to be ((void*)0) and not 0

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#265]
`stddef.h` defines `NULL` to be 0 (an integer). In most contexts this has no importance, due to the automatic promotion to pointer types. This however breaks if `NULL` is used as an argument to a variadic function, on platforms where `int` and `void*` are of different sizes, such as the x86-64 (this also applies to K&R style functions).

```
#include <stdio.h>
#include <stdarg.h>

void print_pointers(unsigned count, ...) {
  va_list ap;
  va_start(ap, count);
  for(unsigned i=0; i<count; i++) {
    printf("%p\n", va_arg(ap, void*));
  }
  va_end(ap);
}

int main() {
  int x, y;
  print_pointers(8, &x, NULL, &y, NULL, &x, NULL, &y, NULL);
  return 0;
}
```

It prints:
```
0x7ffc8b1225f8
(nil)
0x7ffc8b1225fc
(nil)
0x7ffc8b1225f8
0x7f2000000000
0x7ffc8b1225fc
(nil)
```
which is incorrect.

Replacing the definition of `NULL` in `stddef.h` fixes the issue.

**Comment by xavierleroy** [comment]
Thanks (again) for the report.  Fixed by commit d66bd1f.
