### ISSUE TITLE
possible scoping issue in declarations

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#267]
I've come across some code that was doing something like that:
```
char s[]="miaou", buf[sizeof s];
```
This code compiles with `gcc -std=c99 -pedantic` but not with `ccomp`, which complains that `s` is undefined when it tries to get its `sizeof`.

This is not much important, one can easily work around it by using two separate declarations.

**Comment by m-schmidt** [comment]
Thanks for the report. We discovered something similar recently and will investigate.

**Comment by xavierleroy** [comment]
Bug is confirmed.  The following commit by @bschommer fixes it: 99918e41
