### ISSUE TITLE
software division

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#270]
Currently, CompCert can issue function calls for 64-bit integer arithmetic.
Would there be an easy way to get it to issue function calls for 32-bit division and modulo, as well as floating-point division?

**Comment by xavierleroy** [comment]
Look at how the ARM port handles integer division.  Basically, it has operators for division, which are turned into calls to library functions when printing to assembly.  The division operators are described (in arm/Machregs.v) as having fixed input and output registers (corresponding to the calling conventions for the library functions) and destroying all caller-save registers.  I think you can reuse the same trick.
