### ISSUE TITLE
gcc-compatible -z and -shared

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#271]
Would it be possible to implement a `-z` option that does as gcc does (i.e. pass some keywords to the linker)?
Unfortunately many programs assume they will be linked by gcc...

How difficult would it be to implement `-shared`?

**Comment by bschommer** [comment]
I think to have `-shared` we would need to implement `-fpic` which is possible but would need some work. Regarding the `-z`, I'm unsure what it is used for since the gnu linker manual just states that it is ignored for solaris compatibility.

**Comment by xavierleroy** [comment]
CompCert supports the GCC way to pass options to the linker, namely `-Wl,`_opt_,...,_opt_

**Comment by monniaux** [comment]
Unfortunately (and I deplore that), some compilation scripts (from autotools, or perhaps badly used autotools) insist on using `-z`...

**Comment by xavierleroy** [comment]
Being compatible with GCC in order to work around a bug in autotools or elsewhere is not CompCert's objective.  We have limited manpower that we'd rather apply to more interesting problems.
