### ISSUE TITLE
weird constant propagation behavior with respect to instruction selection

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#279]
```
#include <stdint.h>

uint32_t rotate_right3(uint32_t x) {
  return (x >> 3) | (x << (32 - 3));
}

uint32_t rotate_right3v(uint32_t x) {
  const unsigned n = 3;
  return (x >> n) | (x << (32 - n));
}

static inline uint32_t rotate_right(uint32_t x, unsigned n) {
  return (x >> n) | (x << (32 - n));
}

uint32_t rotate_right3i(uint32_t x) {
  return rotate_right(x, 3);
}
```

On x86-64, `rotate_right3` gets compiled to a rotation operation (`rorl`) but `rotate_right3i` and `rotate_right3v` get compiled to two shifts (with constant shift distance) and an or. The pattern-matching for the rotation is missed for some reason.

**Comment by monniaux** [comment]
```
#include <stdint.h>

uint32_t rotate_right3(uint32_t x) {
  return (x >> 3) | (x << (32 - 3));
}

uint32_t rotate_right3v(uint32_t x) {
  const unsigned n = 3;
  return (x >> n) | (x << (32 - n));
}

static inline uint32_t rotate_right(uint32_t x, unsigned n) {
  return (x >> n) | (x << (32 - n));
}

uint32_t rotate_right3i(uint32_t x) {
  return rotate_right(x, 3);
}
```

On x86-64, `rotate_right3` gets compiled to a rotation operation (`'rorl`) but `rotate_right3i` and `rotate_right3v` get compiled to two shifts (with constant shift distance) and an or. The pattern-matching for the rotation is missed for some reason.

**Comment by xavierleroy** [comment]
Instruction selection takes place before constant propagation and before function inlining.  This explains the observations.
