### ISSUE TITLE
-dc -dparse don't work for clightgen

### ISSUE THREAD

**Issue by bcip** [AbsInt/CompCert#298]
I am working on my own copy but there should be the same issue in master branch. When using `clightgen`, flags `-dc` and `-dparse` don't have any actual effect. The following modification should fix this problem.

In `compile_c_file` of `exportclight/Clightgen.ml`, add the following lines:
```
let set_dest dst opt ext =
    dst := if !opt then Some (output_filename sourcename ".c" ext)
      else None in
  set_dest Cprint.destination option_dparse ".parsed.c";
  set_dest PrintCsyntax.destination option_dcmedium ".compcert.c";
  set_dest PrintClight.destination option_dclight ".light.c";
```

**Comment by bschommer** [comment]
Should be fixed by commit 1574cf218bba4372be01c3e4f75e356fadf6f118.
