### ISSUE TITLE
OCaml 4.08.0

### ISSUE THREAD

**Issue by ejgallego** [AbsInt/CompCert#300]
Dear CompCert devs,

we have started testing CompCert with OCaml 4.08.0 in Coq's CI, however a few warnings due to the use of the `Pervasives` module have popped up, and make the build fail.

What would be your preferred approach to handle these?
- disable deprecation warnings in the corresponding places
- unqualify the use of `Pervasives` functions

TIA, Emilio

**Comment by bschommer** [comment]
A PR removing the warnings would be appreciated, since I cannot test the new OCaml version at the moment since there is still no camlp5 release compatible with OCaml 4.08.

**Comment by ejgallego** [comment]
> A PR removing the warnings would be appreciated, since I cannot test the new OCaml version at the moment since there is still no camlp5 release compatible with OCaml 4.08.

Ok, we'll give it a go. camlp5 is compatible with 4.08.0 since a few days, I guess I'll push a new package to OPAM as to help some Coq plugins that still use it.

**Comment by bschommer** [comment]
Yes, but it is also still missing a release, I know that the current master should work with camlp5 but a release is needed for our internal build structure.

**Comment by xavierleroy** [comment]
Thanks for noticing us, Emilio.

I had a look at the uses of `Pervasives`:
* One occurrence of `Pervasives.snd` in a context where there is no risk of confusion with the `snd` extracted from Coq.  So, unqualified `snd` will work just fine.  Besides, the `snd` extracted from Coq would work too :-)
* Seven occurrences of `Pervasives.compare`.  Again, removing the qualification works fine.  It just makes the code a little harder to read in one occurrence.

So, I'm OK with removing the qualification.  When 4.08 is the older version we support, we'll have the option to reintroduce `Stdlib.compare` in some places.

I'll submit a PR shortly.

**Comment by xavierleroy** [comment]
Pull request: #302 .

**Comment by ejgallego** [comment]
Thanks a lot @xavierleroy !

For info, I think that Coq will support OCaml 4.08.0 officially in the 8.11 version [expected at the end of the year], but indeed we want to start testing now so your patch helps a lot.

**Comment by xavierleroy** [comment]
Patch was merged in master sources.

**Comment by ejgallego** [comment]
Thank you @xavierleroy !
