### ISSUE TITLE
Changes in configure broke Windows build

### ISSUE THREAD

**Issue by MSoegtropIMC** [AbsInt/CompCert#304]
Dear CompCert Team,

a recent change in the configure file, I think it was 1df887f5a275e4c31096018ff1a8fdfc39bca591, broke the Windows build. The menhir library path ended up to contain a carriage return. I will provide a PR to fix this. This also hardens configure for menhir installations which return a path with backward slashes.

Best regards,

Michael

**Comment by xavierleroy** [comment]
Thanks for the report.  CI includes a Windows+Cygwin machine, which did not run into this problem.  But I guess it depends on the Cygwin version used, as we had similar issues with OCaml in the past.

**Comment by MSoegtropIMC** [comment]
Thanks for merging it quickly - I will remove the patch for Coq then!

> But I guess it depends on the Cygwin version used, as we had similar issues with OCaml in the past.

The CompCert build delivered with Coq is a MinGW build - it is build using Cygwin in a sort of cross compilation. This has the effect that tools like the OCaml compiler or Menhir are MinGW executables which append a CR to every line of output. Plain cygwin builds of OCaml or Menhir wouldn't do that.
