### ISSUE TITLE
-Wliteral-range warning for INFINITY/HUGE_VAL

### ISSUE THREAD

**Issue by maroneze** [AbsInt/CompCert#308]
While doing some differential compiler tests, I noticed that, if I compile a program with `INFINITY` or `HUGE_VALF`, I get the following warning:

    #include <math.h>
    double f = HUGE_VALF; // warning: magnitude of floating-point constant too large for
                          // type 'float' [-Wliteral-range]

I am unable to produce the same results on Clang (where the option is enabled by default). I would just like to know if this is deliberate or if Clang and CompCert should agree on this.

**Comment by xavierleroy** [comment]
Please check the code after macro expansion (`ccomp -E`).  

On Glibc/Linux for example, there are several definitions of `HUGE_VAL`, some specific to GCC, others involving (voluntary) overflow in FP literals.  Clang claims to be GCC, so it probably sees a different definition than CompCert.

**Comment by bschommer** [comment]
Even in other libraries it is often comment that these macros expand to specialized builtin constants for GCC and compiler claiming to be GCC, such as clang. Note that some libraries don't even have a valid definition for these macros to be used in all contexts.

**Comment by maroneze** [comment]
Ok, thank you for the clarifications.
