### ISSUE TITLE
A possible case of miscompilation in CompCert 3.5

### ISSUE THREAD

**Issue by nanokatze** [AbsInt/CompCert#312]
Hello!  First and foremost, I am not absolutely certain if the following is a compiler or a library issue, though from my observation it appears to be the former.

I am compiling https://github.com/ARMmbed/mbed-crypto tag mbedcrypto-1.1.1 with CompCert 3.5, host and target are Fedora 30 5.1.20-300 x86_64, toolchain is taken from GCC 9.1.1, using
```
make test CC=ccomp CFLAGS='-O1 -fbitfields -fstruct-passing -finline-asm' WARNING_CFLAGS= DEBUG=1 -j
```
The library's test suite test_suite_psa_crypto (this specific suite can be run standalone by running ./test_suite_psa_crypto in tests directory) has two tests fail:
```
PSA key derivation: HKDF SHA-256, RFC5869 #1, output 42+0 ......... FAILED
  ( ( psa_key_derivation( &generator, handle, alg, salt->x, salt->len, label->x, label->len, requested_capacity ) ) ) == ( ((psa_status_t)0) )
  at line 4248, suites/test_suite_psa_crypto.function
```
and
```
PSA key derivation: HKDF SHA-256, exercise HKDF-SHA-256 ........... FAILED
  ( ( psa_key_derivation( &generator, handle, alg, label, label_length, seed, seed_length, sizeof( output ) ) ) ) == ( ((psa_status_t)0) )
  at line 532, suites/test_suite_psa_crypto.function
```
The control flow for the 2nd failing test is as follows:
1. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/tests/suites/test_suite_psa_crypto.function#L532
2. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/library/psa_crypto.c#L4296
3. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/library/psa_crypto.c#L4211
4. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/library/psa_crypto.c#L4042
5. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/library/psa_crypto.c#L1985
6. https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/library/psa_crypto.c#L1390

It appears that `psa_crypto_generator_t generator` in
https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/tests/suites/test_suite_psa_crypto.function#L523, or at least its `.ctx.hkdf.hmac.hash_ctx.alg` member field
somehow ends up uninitialized despite `PSA_CRYPTO_GENERATOR_INIT` being defined to `{0, 0, {{0, 0}}}` (see https://github.com/ARMmbed/mbed-crypto/blob/mbedcrypto-1.1.1/include/psa/crypto_struct.h#L220).

To make presence of garbage data evident, one might add 
```c
    TEST_EQUAL(generator.ctx.hkdf.hmac.hash_ctx.alg, 0);
```
to functions exercise_key_derivation_key and derive_output at lines 529 and 4228 respectively in tests/suites/test_suite_psa_crypto.function.

The issue seems to not manifest itself if memory is explicitly zeroed using
```c
    memset(&generator, 0, sizeof(generator));
```
```c
    uint8_t x[sizeof(generator)] = {0};
    memcpy(&generator, x, sizeof(x));
```
or
```c
    mbedtls_platform_zeroize(&generator, sizeof(generator));
```

The assembly output for (modified part of exercise_key_derivation_key)
```c
    asm("int3" ::: "memory");
    psa_crypto_generator_t generator = PSA_CRYPTO_GENERATOR_INIT;
    asm("int3" ::: "memory");
```
is (inlined into exercise_key)
```
  402646:       cc                      int3   
    psa_crypto_generator_t generator = PSA_CRYPTO_GENERATOR_INIT;
  402647:       45 31 c0                xor    %r8d,%r8d
  40264a:       44 89 84 24 b0 00 00    mov    %r8d,0xb0(%rsp)
  402651:       00 
  402652:       48 31 c9                xor    %rcx,%rcx
  402655:       48 89 8c 24 b8 00 00    mov    %rcx,0xb8(%rsp)
  40265c:       00 
  40265d:       4d 31 c9                xor    %r9,%r9
  402660:       4c 89 8c 24 c0 00 00    mov    %r9,0xc0(%rsp)
  402667:       00 
  402668:       48 31 c0                xor    %rax,%rax
  40266b:       48 89 84 24 c8 00 00    mov    %rax,0xc8(%rsp)
  402672:       00 
    asm("int3" ::: "memory");
  402673:       cc                      int3   
```
but the sizeof(psa_crypto_generator_t)=520.

For comparison, of
```c
    asm("int3" ::: "memory");
    memset(&generator, 0, sizeof(generator));
    asm("int3" ::: "memory");
```
the assembly output is as follows
```
    asm("int3" ::: "memory");
  402825:       cc                      int3   
    memset(&generator, 0, sizeof(generator));
  402826:       48 8d bc 24 b0 00 00    lea    0xb0(%rsp),%rdi
  40282d:       00 
  40282e:       31 f6                   xor    %esi,%esi
  402830:       48 c7 c2 08 02 00 00    mov    $0x208,%rdx
  402837:       e8 c4 e8 ff ff          callq  401100 <memset@plt>
    asm("int3" ::: "memory");
  40283c:       cc                      int3
```

The issue is also present when the compiler used is CompCert 3.4.  The issue is *not* present when the compiler used is GCC 9.1.1 or clang 8.0.0 when running with -fsanitize=address,undefined.

**Comment by m-schmidt** [comment]
Can you compile the file containing the structure initialization with the additional option `-dc` and attach the output (the generated output has file extension `.compcert.c`)

**Comment by nanokatze** [comment]
Lines 5369 and 20556

[test_suite_psa_crypto_init.compcert.c.txt](https://github.com/AbsInt/CompCert/files/3473289/test_suite_psa_crypto_init.compcert.c.txt)

**Comment by nanokatze** [comment]
This is an isolated one that too reproduces the issue
[miscompcert.c.txt](https://github.com/AbsInt/CompCert/files/3473316/miscompcert.c.txt)
[miscompcert.compcert.c.txt](https://github.com/AbsInt/CompCert/files/3473317/miscompcert.compcert.c.txt)

**Comment by m-schmidt** [comment]
Thanks, we will have a look.

**Comment by xavierleroy** [comment]
Thank you for the very detailed repro cases, we'll work from there.

In the Asm output the initialization code looks correct to me: there is 32 bits of padding between the `alg` and `capacity` fieds of `struct psa_crypto_generator_s` that CompCert does not initialize, but this is allowed by the C standard. 

Could it be that the tests assume that this padding is set to zero?  That would be an incorrect assumption.

**Comment by nanokatze** [comment]
This the simplest one I came up with so far and has no dependencies
[miscompcert2.c.txt](https://github.com/AbsInt/CompCert/files/3473353/miscompcert2.c.txt)
[miscompcert2.compcert.c.txt](https://github.com/AbsInt/CompCert/files/3473354/miscompcert2.compcert.c.txt)

**Comment by xavierleroy** [comment]
Thank you for shrinking the repro case so much!

There is no miscompilation in the latest example (miscompcert2).  Unless you use C99 designators, only the first member of a union type is initialized. In your example, `alpha` is initialized to zero, but the struct containing `beta` and `gamma` is not.   

Standard reference: ISO C 99, section 6.7.8, paragraph 17: 
_Each brace-enclosed initializer list has an associated current object. When no designations are present, subobjects of the current object are initialized in order according to the type of the current object: array elements in increasing subscript order, structure members in declaration order, **and the first named member of a union**._

**Comment by nanokatze** [comment]
Aha, excuse me then. Is it fine to close the issue then?

**Comment by xavierleroy** [comment]
Continuing your example: because you've used an anonymous struct as a member of `union A`, I don't think C2011 makes it possible to designate this anonymous struct for initialization to 0.  (C2011 because anonymous struct members are not in C1999.)  Your best bet is to `memset` the whole struct to 0.

If you name the struct member, here is what you can write:
```
union A {
	int alpha;
	struct {
		int beta;
		int gamma;
	} s;
};

static void
test(void)
{
	union A a = {.s = {0}};

	assert(a.s.gamma == 0);
}
```
and I'm confident this is compiled correctly.

**Comment by xavierleroy** [comment]
> Aha, excuse me then. Is it fine to close the issue now?

You are definitely excused!  However, if my explanation is right, it means something is wrong (compiler-dependent, not portable) in mbed-crypto or in its test suite.  Maybe this should be brought to the attention of the mbed-crypto developers?  If they disagree, we are in for an interesting fight :-)

**Comment by nanokatze** [comment]
> However, if my explanation is right, it means something is wrong (compiler-dependent, not portable) in mbed-crypto or in its test suite. Maybe this should be brought to the attention of the mbed-crypto developers? If they disagree, we are in for an interesting fight :-)

Indeed it is, I am already writing an issue to mbed-crypto.  Thank you for your explanation!

**Comment by gilles-peskine-arm** [comment]
Mbed Crypto here. (Hi Xavier!) I agree, it's fine for a compiler not to initialize padding or parts of a union that aren't in the union member that's being initialized. Our code shouldn't be accessing the uninitialized fields. Now to find where that bug is!
