### ISSUE TITLE
fdisk on OpenBSD crashes when compiled with CompCert

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#32]
(This report is for the struct-passing branch).

fdisk on OpenBSD crashes randomly when compiled with CompCert. I've created a reduced test case:
http://dickman.org/compcert/test24/ccomp/foo.c

The CompCert version alternates between segfaulting and printing 0 instead of the expected AA55:

```
$ ./gcc/foo
dmbr_sign=AA55
$ ./ccomp/foo
Segmentation fault (core dumped)
$ ./ccomp/foo
dmbr_sign=0
```

The code in foo.c does the following:
- read the first 512 byte sector (the master boot record) from disk wd0
- memcpy the char* data into a struct dos_mbr
- print out the MBR signature (the last 2 bytes of the MBR).

All gcc and CompCert outputs were saved here:
http://dickman.org/compcert/test24/

**Comment by xavierleroy** [comment]
Well, with CompCert, sizeof(struct dos_mbr) = 516, so the memcpy ends  up copying 516 bytes from the 512-byte buffer.  That might explain the random behavior, or not. 

Now, why is the size 516 instead of 512?  Apparently, the __attribute__((__packed__)) was stripped off during preprocessing.  (It's not in foo.i.)  If I add it back to foo.i, sizeof(struct dos_mbr) = 512 as expected.

**Comment by didickman** [comment]
Oh thanks. I should have caught that. I see that gcc 4.2.1 strips it off when "-U__GNUC__" is specified in the below:
gcc -U__GNUC__ -E -I/usr/local/lib/compcert foo.c

**Comment by didickman** [comment]
I don't know if this is a bug in the pre-processor but it seems like if you have -U__GNUC__ and have any #include directives, the attribute((packed)) gets stripped out. If you have no #include directives, the attribute stays. I couldn't find anything documenting this behaviour:

```
$ cat foo.c
#include <limits.h>

struct S {
        int a;
} __attribute__((__packed__));
$ gcc -E -U__GNUC__ foo.c | tail -3
struct S {
        int a;
} ;
```

Without any #include directives:

```
$ cat foo2.c
struct S {
        int a;
} __attribute__((__packed__));

$ gcc -E -U__GNUC__ foo2.c
# 1 "foo2.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "foo2.c"
struct S {
        int a;
} __attribute__((__packed__));
```

**Comment by didickman** [comment]
Solved locally on OpenBSD after some help from stackoverflow: http://stackoverflow.com/questions/29312645/why-does-gcc-unexpectedly-strip-attribute-packed
