### ISSUE TITLE
Why can't compcert recognize u_char type?

### ISSUE THREAD

**Issue by QuXing9** [AbsInt/CompCert#322]
Hi, 
I defined a variable of u_char type in the code and compcert could’t compile it, compiler threw an error: syntax error after 'u_char' and before 'NISLParameter1'. The u_char type is defined in header file “sys/types.h”, and I have referenced it in the code.

TestCase:
1  #include<sys/types.h>
2  #include<stdio.h>
3  void main(){
4      u_char NISLParameter1 = 'x';
5  }

Command:
./compcert/version3.6/bin/ccomp -c testcase.c

Complier Version:
version 3.6

Output:
testcase.c:4:8: syntax error after 'u_char' and before 'NISLParameter1'.
Up to this point, an expression has been recognized:
  　'u_char'
If this expression is complete,
then at this point, a semicolon ';' is expected.
Fatal error; compilation aborted.
1 error detected.

Expected output:
Compile successfully

Is this right for Compcert? Looking forward to your reply.

**Comment by bschommer** [comment]
Similar to #323, could you please provide the output of `ccomp -E`? Note that CompCert is an ISO C compiler and does not support all extensions of gcc or clang.

**Comment by jhjourdan** [comment]
Indeed, `u_char` is a GNU extension, not supported by the GNU standard. If you compile with `gcc -std=c99`, you will get a similar error. This has nothing to do with CompCert.

**Comment by QuXing9** [comment]
> Indeed, `u_char` is a GNU extension, not supported by the GNU standard. If you compile with `gcc -std=c99`, you will get a similar error. This has nothing to do with CompCert.

I tried this problem with gcc, which is exactly what you said. Thank you. I'll pay attention to it next time.

**Comment by QuXing9** [comment]
> Similar to #323, could you please provide the output of `ccomp -E`? Note that CompCert is an ISO C compiler and does not support all extensions of gcc or clang.

Here is the source c file and preprocessed file.
[compcert_uchar.zip](https://github.com/AbsInt/CompCert/files/3916032/compcert_uchar.zip)

**Comment by bschommer** [comment]
As explained by @jhjourdan this is due to a none standard gcc extension that is not supported by CompCert.
