### ISSUE TITLE
Why can’t compcert compile header file “sys/ucontext.h” ?

### ISSUE THREAD

**Issue by QuXing9** [AbsInt/CompCert#323]
Hi, 
stack_t is used in header file ucontext.h to define the struct ucontext. stack_t type is declared in header file “bit/sigstack.h”. “bit/sigstack.h” is inlined by “signal.h”. And “signal.h” is inlined by “ucontext.h”. So, Using stack_t in “ucontext.h” should be correct. But compcert throws an error: syntax error after ';' and before 'stack_t'. 

TestCase:
1  #include<stdio.h>
2  #include<signal.h>
3  #include<sys/ucontext.h>
4  void main(){
5  }

Command:
./compcert/version3.6/bin/ccomp -c testcase.c

Complier Version:
version 3.6

Output:
/usr/include/x86_64-linux-gnu/sys/ucontext.h:137:5: syntax error after ';' and before 'stack_t'.
Ill-formed declaration.
The following identifier is used as a type, but has not been defined as such:
  'stack_t'
Fatal error; compilation aborted.
1 error detected.

Expected output:
Compile successfully

Is this right for Compcert? Looking forward to your reply.

**Comment by jhjourdan** [comment]
I cannot reproduce. Could you please provide the preprocessed file (by using gcc -E)?

**Comment by jhjourdan** [comment]
> I cannot reproduce. Could you please provide the preprocessed file (by using gcc -E)?

Sorry: could you instead use `ccomp -E`?

**Comment by QuXing9** [comment]
> I cannot reproduce. Could you please provide the preprocessed file (by using gcc -E)?

Here are the C source file and preprocessed file. Perhaps the stack_t type is also a GNU extension.
[compcert_ucontext.zip](https://github.com/AbsInt/CompCert/files/3916045/compcert_ucontext.zip)

**Comment by bschommer** [comment]
The problem is the header uses the type stack_t but it is nowhere defined, so CompCert complains correctly. The problem is that you do not set the right defines before including the header files as explained [here](https://stackoverflow.com/questions/20778735/is-the-type-stack-t-no-longer-defined-on-linux).
