### ISSUE TITLE
Observable behavior and volatile accesses to non-global variables

### ISSUE THREAD

**Issue by sayon** [AbsInt/CompCert#336]
Currently the observable (= external ) behavior of  a program, as defined in `common/Events.v` and `common/Behaviors.v`, incorporates a trace of events, some of which are volatile reads and writes to _global_ variables.

The C18 standard, however, defines the observable behavior in 5.1.2.3/6 by:

> Volatile accesses to objects are evaluated strictly according to the rules of the abstract machine.

where volatile accesses are defined in 5.1.2.3/2 as follows:

> An access to an object through the use of an lvalue of volatile-qualified type is a volatile access.

It seems to me that all volatile accesses should occur in the trace, no matter which kind of memory is referred.
 
Is this a deliberate simplification? If so I would add a small comment regarding that in `common/Events.v`; I know that CompCert C semantics does not describe the standard to the letter.

**Comment by xavierleroy** [comment]
There is a technical reason for generating events for volatile accesses only if the access is to a global variable: accesses in the stack or even in dynamically-allocated memory do not have "well-defined" addresses, in the sense that stack layout, for instance, may change during compilation, and in different ways depending on the optimization level.  So, we could definitely report an event "a volatile memory access occured", but not at which address it occurred, which is not very useful. 

While we're quoting the standards, C11 (on which CompCert is based) says (section 6.7.3 para 7):
> What constitutes an access to an object that has volatile-qualified type is implementation-defined.

This gives so much leeway to the implementation that the standard becomes vacuous w.r.t. volatile accesses.  Common-sense reasoning is better.

**Comment by sayon** [comment]
Thanks @xavierleroy this clarifies it. 

For the future, is there a dedicated place for discussions about CompCert C semantics? I might have a couple of points to discuss.
