### ISSUE TITLE
support for _Static_assert

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#339]
Some GNU autoconfiguration use awfully ugly tricks to perform static assertions, and some of these tricks fail on CompCert. Maybe supporting `_Static_assert`, for clean, kludge-free support, would be nice.

**Comment by xavierleroy** [comment]
Thanks for the suggestion.  I didn't realize that `_Static_assert` was part of C11.  It looks like a feature CompCert should support, indeed.

**Comment by christoph-cullmann** [comment]
I guess this can be considered to be implement with commit a8ce85adbf2863e98e5c24e9cc6f82947d4b3a29.
