### ISSUE TITLE
NaNs: compiler and interpreter DISAGREE on aarch64

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#341]
$ git rev-parse HEAD
039b532ae972292ec2f726505422afd49569b738
$ cd test/regression
$ make -j4 CCOMPOPTS=-static
$ make test
NaNs: compiler and interpreter DISAGREE

Using qemu for running the tests. is this expected ?

**Comment by m-schmidt** [comment]
We had similar problems (e.g. flipped least significant bits) with QEmu in FP-computations for PowerPC. A comparison with real hardware always showed that QEmu was wrong.

**Comment by bschommer** [comment]
Which version of qemu are you using for testing, there are some issues with `NaN` in some versions of qemu.

**Comment by xavierleroy** [comment]
All the versions of QEMU I've used so far do not simulate NaN payloads: they just use the FP arithmetic of the host processor (typically x86), NaN payloads included.  So, the NaN test is not reliable on QEMU.  But it succeeds if the CompCert-compiled code is run on true ARMv8 hardware, such as the Odroid N2 I use for testing.

**Comment by xavierleroy** [comment]
I'm taking the liberty of closing this PR, as there is no CompCert issue there.
