### ISSUE TITLE
raytracer in test suite crashes with an assertion failure

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#342]
```
$ git rev-parse HEAD
039b532ae972292ec2f726505422afd49569b738
$ cd test/raytracer
$ make CCOMPOPTS=-static all
$ /opt/qemu/4.2.0/bin/qemu-arm ./render <kal.gml 
render: intersect.c:323: inside_bs: Assertion `obj->radius >= 0.0' failed.
```

Same behavior on an actual ARM platform (Cortex A53)

Same on CompCert 3.6 and 3.4

**Comment by xavierleroy** [comment]
I cannot reproduce, neither with qemu nor with a Raspberry-3.  Care to give more details about the build OS, the version of binutils, etc?

**Comment by xavierleroy** [comment]
Also, is this ARM-HF or ARM-EABI?

**Comment by monniaux** [comment]
Apologies. Due to a misconfiguration on our part, we linked against arm-gnueabihf libraries while compiling with CompCert configured for arm-gnueabi.
