### ISSUE TITLE
ABI mismatch on aarch64 (bitfields ?)

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#344]
```
$ git rev-parse HEAD
039b532ae972292ec2f726505422afd49569b738
```

See attached tarball. The program, produced by yarpgen, supposedly yields a well defined result independent of the architecture. It does indeed yield the same result if compiled with gcc on x86-64, gcc on AAarch64, CompCert on AAarch64. Yet it gives different results if one of the modules (`init.c`)  is not compiled with the same compiler as the others. There seems to be an ABI mismatch. It may have to do with bit fields.

[ran000003.tar.gz](https://github.com/AbsInt/CompCert/files/4397150/ran000003.tar.gz)

**Comment by xavierleroy** [comment]
Yes, CompCert does not 100% conform to ELF ABIs, in particular concerning bit-field layout.  The ABI incompatibilities are meticulously documented in the CompCert user's manual, http://compcert.inria.fr/man/manual001.html#sec11.  See in particular the last section "Layout of bit-fields in struct types".  

In the future, please refrain from submitting ABI incompatibiliies as issues when they are already known and documented.  We are aware of the problem, we don't have easy fixes yet, and piling up Github issues is not going to help.
