### ISSUE TITLE
Make clean misses a directory

### ISSUE THREAD

**Issue by anshumanmohan** [AbsInt/CompCert#349]
Perhaps minor and oddly specific, but ```make clean``` does not appear to clear cparser/MenhirLib/, which can get filled with precompiled .vo files and cause magic number-based hiccups when ```make```ing. I removed the offending .vo files from that directory by hand, and then a standard ```make clean``` + ```configure``` + ```make``` worked fine.

**Comment by bschommer** [comment]
The reason ist that the directory moved to the toplevel directory. You should probably remove the `cparser/MenhirLib` directory.

**Comment by anshumanmohan** [comment]
Got it, thank you!
