### ISSUE TITLE
Put volatile-ness information inside memory?

### ISSUE THREAD

**Issue by alxest** [AbsInt/CompCert#350]
Currently, volatile-ness information is placed in global environments, not memory.
I was wondering if we can put this information inside memory (during the loading phase) so that we can bypass global environments -- just like how `gvar_init` and `gvar_readonly` is treated.
This would lead to somewhat cleaner and more flexible code in my project.

.
Here is a longer version.
- Cleaner code: In my project (CompCertM), I have a notion of *world*, which contains src/tgt memory, injection, and some auxiliary data.
It is desirable to make this data to be only aware of the memory, not global environments, but I cannot do this for now.
Suppose we have the following global environtment/injection at external call state.
```
src: (Genv.find_symbol "a" == 1) && (Genv.block_is_volatile 1 == FALSE)
tgt: (Genv.find_symbol "a" == 1) && (Genv.block_is_volatile 1 == TRUE)
meminj does not connect src/tgt block 1 (both are private)
```
Then, the possible futures worlds (injections) should *not* connet src/tgt block 1, because it will break `symbols_inject` condition.
I do this reasoning by putting `Genv.genv_next` data in the world && quantify `inject_separated` condition w.r.t. this data. (similar with `ec_mem_inject`)
However, if volatile-ness condition was placed in memory and `Mem.inject` states proper conditions, I guess I can avoid putting `Genv.genv_next` data and `inject_separated` condiiton.
- More flexible: Suppose we want to prove the refinement between the following codes.

```
static int x = 0;
static bool publicized = false;

void add() {
  if(!publicized) x++;
  else UB
}

int get() {
  if(!publicized) return (x);
  else UB
}

int* publicize() {
  publicize = true;
  x = 42;
  return &x;
}
```

```
static int x = 0;
static bool publicized = false;

void add() {
  if(!publicized) x--;
  else UB
}

int get() {
  if(!publicized) return (-x);
  else UB
}

int* publicize() {
  publicized = true;
  x = 42;
  return &x;
}
```

In the early stage of an execution, the injection should *not* connect `x` and state proper relational invariants (`x_tgt = -x_src`).
However, when `publicize` is called, we *should* connect `x` because its address is leaked.
This is not allowed by current `inject_separated` condition.

**Comment by xavierleroy** [comment]
> Currently, volatile-ness information is placed in global environments, not memory. I was wondering if we can put this information inside memory (during the loading phase) so that we can bypass global environments -- just like how gvar_init and gvar_readonly is treated.

I'm going to answer with a prudent "perhaps"...  

Currently, from the standpoint of the memory model, volatile locations are just locations with Nonempty permissions, i.e. locations that cannot be read, written, nor freed.  The interpretation of certain memory accesses as volatile accesses is done "above", in the Events machinery.

Note that the current handling already prevents a memory injection from connecting a global, volatile variable with a global, non-volatile variable: the permissions would not match!

Perhaps we could have a specific permission for volatile locations, different from and incompatible with the existing freeable / writable / readable / nonempty permissions.  I'm not sure this would solve all your CompCertM issues: the Events machinery that decides whether a memory access is volatile or plain still needs global environments to produce the appropriate event in the former case.

Your second example (with the `publicized` flag) has no volatile variables in it, so I don't see the connection.  I have the feeling that if you want to reason compositionally (e.g. function per function) about this refinement, you'll need a relational program logic significantly more powerful than just a memory injection.

**Comment by xavierleroy** [comment]
I'm closing this report, as not enough information was provided to understand the needs and consider extending the memory model.  @alxest is welcome to contact me by e-mail to discuss the issue further.
