### ISSUE TITLE
a use-after-scope issue

### ISSUE THREAD

**Issue by helloqirun** [AbsInt/CompCert#356]
The following code has a use-after-scope issue.

```
int main() {
  int c;
  int *a;
  {
    int b=1;
    a = &b;
  }
  c=*a;
  printf("%d\n",c);
}
```

It appears that compcert (3.9) concludes that *a can still point to b. See the output with "comp -interp -fall -trace":
```
--[red_var_local]-->
Time 20: in function main, expression <loc c> = *<loc a>
--[red_rvalof]-->
Time 21: in function main, expression <loc c> = *<ptr b>
--[red_deref]-->
Time 22: in function main, expression <loc c> = <loc b>
--[red_rvalof]-->
Time 23: in function main, expression <loc c> = 1
```

Should compcert emit an undefined behavior error here?

**Comment by xavierleroy** [comment]
CompCert C does not have block-scoped variables, only function-scoped variables.  The code that `ccomp -interp` executes is actually the following:
```
int main(void)
{
  int c;
  int *a;
  int b;
  b = 1;
  a = &b;
  c = *a;
  printf(__stringlit_1, c);
  return 0;
}
```
and there is no use-after-scope.  

If you run `ccomp -interp -dc`, the `-dc` option causes the CompCert C form of the program to be printed in C syntax in a `.compcert.c` file.  This is the form that is being interpreted.
