### ISSUE TITLE
clightgen -short-idents occasionally uses a -canonical-ident by mistake

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#358]
In the current CompCert master branch (0eba6f63b6bc458d856e477f6f8ec6b78ef78c58), running clightgen -short-idents, sometimes one identifier is still defined using the $ notation.

See attached zip file (containing hash.c and output hash.v) for example; here's an excerpt:

```
Definition ___compcert_va_int32 : ident := 23%positive.
Definition ___compcert_va_int64 : ident := 24%positive.
Definition _b : ident := $"b".
Definition _buckets : ident := 5%positive.
Definition _c : ident := 67%positive.
```

[hash.zip](https://github.com/AbsInt/CompCert/files/4690823/hash.zip)
`hash.v` produced with `clightgen -normalize -short-idents hash.c`

**Comment by andrew-appel** [comment]
In addition,  `clightgen --help`  gives the wrong description of -short-idents.

**Comment by xavierleroy** [comment]
That's called a collision!  In your example, `b` happens to be numbered 75, which is equal to the canonical encoding of `"b"`, so clightgen was happy to produce `$"b"` as a nicer(?) alternative to `75`.

I agree this is confusing and best avoided.  Commit 18859319 makes sure the `$"..."` notation is never used in `-short-idents` mode.

Commit 08491de0 fixes the error message.
