### ISSUE TITLE
clightgen weird behavior with annotations

### ISSUE THREAD

**Issue by p3rsik** [AbsInt/CompCert#360]
Hello!
I tried to use general annotation mechanism and got some weird behavior:
When compiling this C code using clightgen version 3.6
```
int f(int *p) {
  // p is not null
  __builtin_annot("_p <> nullval");
  int t = *p;
  return t;
}
```
Got this output in **.v** file:
```
Definition f_f := {|
  fn_return := tint;
  fn_callconv := cc_default;
  fn_params := ((_p, (tptr tint)) :: nil);
  fn_vars := nil;
  fn_temps := ((_t, tint) :: nil);
  fn_body :=
(Ssequence
  (Sbuiltin None (EF_annot "_p <> nullval" nil) Tnil nil)
  (Ssequence
    (Sset _t (Ederef (Etempvar _p (tptr tint)) tint))
    (Sreturn (Some (Etempvar _t tint)))))
|}.
```
We're specifically interested in `EF_annot`, that has `EF_annot : positive -> string -> list typ -> external_function` type. As you can see, it's not fully applied, it's missing positive argument.
Is this a bug? Is it fixed in 3.7 version?

Also, there is a definition at the end of the file that looks like this:
```
Definition assertions (txt: string) args : Prop :=
  match txt, args with
  | "_p <> nullval"%string, nil =>
    _p <> nullval
  | _, _ => False
  end.
```
What is it for? I didn't find any documentation about this feature in official compcert docs.

**Comment by xavierleroy** [comment]
> We're specifically interested in EF_annot, that has EF_annot : positive -> string -> list typ -> external_function type. As you can see, it's not fully applied, it's missing positive argument.
Is this a bug? 

Yes.  clightgen wasn't updated following commit 6a010b47.  This will be fixed soon.

> Also, there is a definition at the end of the file that looks like this:

This was a very experimental feature that was never used.  This was intended to enable programmers to write logical assertions in the source, as `__builtin_annot` annotations carrying a Coq proposition parameterized by the values of some variables or expressions.  I think it's time to remove this feature, as it clashes with other possible uses of annotations.

**Comment by p3rsik** [comment]
Thank you, just to clarify, `clightgen` from compcert 3.7 still has this bug, so I want to wait for the next release, right?

**Comment by xavierleroy** [comment]
> clightgen from compcert 3.7 still has this bug,

Yes.  I'll let you know when it is fixed on the Git master.

**Comment by p3rsik** [comment]
Thank you very much)

**Comment by p3rsik** [comment]
Thank you for your work, I'll try working from master sources
