### ISSUE TITLE
clightgen has trouble with assert on MacOSX

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#361]
In CompCert 3.7 or 3.5,

`clightgen -normalize`  correctly translates `assert(...)` on linux and cygwin, but generates bad code on MacOSX.  (The -normalize flag may be irrelevant, but that's the way I happened to test it.)

Test case:
```
#include <assert.h>
void f(int x) {  assert (x>0); }
```
The definition of the assert macro, in standard system assert.h, is translated properly by clightgen on Cygwin or Linux.  On Cygwin it is,
```
# define assert(__e) ((__e) ? (void)0 : __assert_func (__FILE__, __LINE__, \
						       __ASSERT_FUNC, #__e))
```
from which `clightgen -normalize`  translates  `assert(x>0)` into the following very reasonable Clight code (and similar on Linux):
```
(Sifthenelse (Ebinop Ogt (Etempvar _x tint) (Econst_int (Int.repr 0) tint)
               tint)
  Sskip
  (Scall None
    (Evar ___assert_func (Tfunction
                           (Tcons (tptr tschar)
                             (Tcons tint
                               (Tcons (tptr tschar)
                                 (Tcons (tptr tschar) Tnil)))) tvoid
                           cc_default))
    ((Evar ___stringlit_2 (tarray tschar 7)) ::
     (Econst_int (Int.repr 2) tint) :: (Evar ___func__ (tarray tschar 2)) ::
     (Evar ___stringlit_1 (tarray tschar 4)) :: nil)))
```
But on MacOSX, the definition of assert is (`/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/assert.h`)
```
#define assert(e)  \
    ((void) ((e) ? ((void)0) : __assert (#e, __FILE__, __LINE__)))
```
Notice that there's an extra cast-to-void.  The translation into Clight is,
```
(Sifthenelse (Ebinop Ogt (Etempvar _x tint) (Econst_int (Int.repr 0) tint)
               tint)
  (Sset _t'1 (Ecast (Ecast (Econst_int (Int.repr 0) tint) tvoid) tvoid))
  (Ssequence
    (Ssequence
      (Scall (Some _t'2)
        (Evar _printf (Tfunction (Tcons (tptr tschar) Tnil) tint
                        {|cc_vararg:=true; cc_unproto:=false; cc_structret:=false|}))
        ((Evar ___stringlit_3 (tarray tschar 30)) ::
         (Evar ___stringlit_2 (tarray tschar 7)) ::
         (Econst_int (Int.repr 2) tint) ::
         (Evar ___stringlit_1 (tarray tschar 4)) :: nil))
      (Scall (Some _t'3) (Evar _abort (Tfunction Tnil tvoid cc_default)) nil))
    (Sset _t'1 (Ecast (Etempvar _t'3 tvoid) tvoid))))
```
This is bad:  it contains "cast 0 to void and assign to variable", which is legal in C but not in Clight, unless I am mistaken.  Even it if is legal in Clight, it's very unpleasant, and VST cannot verify it.

Proposed solution: "cast constant to void" should be pretty-printed by clightgen as "Sskip".  Then, in the MacOSX case, there will be an unused temp variable, but that will cause no harm.

Thanks to @akravc for noticing this problem.

**Comment by xavierleroy** [comment]
Just to give some context: the code above is correct Clight.

In ISO C and in CompCert C, it is not possible to assign to an l-value of type void, as in
```
  void * p; ... *p = (void) 0;
```
This is also the case in Clight for assignments to l-values (Sassign) but not for assignments to temporary variables (Sset).  The idea is that a temporary variable should be able to hold the value of any subexpression, including a subexpression of type void.

Now there might be ways to avoid generating those "void-value" assignments to temporary variables, at least in common cases.  I'll give it a try.

**Comment by andrew-appel** [comment]
I suppose it would also be possible to add a proof rule to VST to handle void-Sset, but indeed it would be convenient if clighten handled this case.

**Comment by xavierleroy** [comment]
From a closer look, it seems easy to eliminate casts (to void in particular) that occur at the top of an expression, in statement position.  This would fix the issue with the macOS `assert` macro, and also produce better-looking Clight code when a function call is cast to void (`(void) printf(...)`).  I'll work this out in the coming days.

In general, I'm afraid there will always be artificial examples made up from nested conditional expressions, casts to void, and calls to functions returning void that will trigger assignment of a value of type void to a Clight temporary.  So, the extra proof rule could be useful too.

**Comment by xavierleroy** [comment]
Commit 070babef on the master branch should fix the issue.

For example, consider the C source
```
#include <stdio.h>

extern void __assert(char *, char *, int);

#define assert(e)  \
    ((void) ((e) ? ((void)0) : __assert (#e, __FILE__, __LINE__)))

int main(int argc, char ** argv)
{
  assert(argc > 0);
  (void) printf("%d\n", argc);
  return 0;
}
```
Before this commit it was translated to the following Clight code, with unpleasant assignments of void values to Clight temporaries:
```
int main(int argc, signed char **argv)
{
  register int $64;
  register void $63;
  register void $62;
  if (argc > 0) {
    $62 = (void) (void) 0;
  } else {
    $63 = __assert(__stringlit_2, __stringlit_1, 10);
    $62 = (void) $63;
  }
  $64 = printf(__stringlit_3, argc);
  return 0;
  return 0;
}
```

With the commit, we now get:
```
int main(int argc, signed char **argv)
{
  if (! (argc > 0)) {
    __assert(__stringlit_2, __stringlit_1, 10);
  }
  printf(__stringlit_3, argc);
  return 0;
  return 0;
}
```
That's much nicer Clight code, indeed.

**Comment by andrew-appel** [comment]
Thank you.
