### ISSUE TITLE
Menhir sometimes suggests a wrong menhirlib location; defend against it?

### ISSUE THREAD

**Issue by xuanruiqi** [AbsInt/CompCert#363]
Sometimes, `menhir --suggest-menhirLib` returns a wrong location. For example, in the Arch Linux package, we use `dune install --prefix "${pkgdir}/usr" --libdir "${pkgdir}$(ocamlfind printconf destdir)"` to install Menhir, but the location suggested by `menhir --suggest-menhirLib` is wrong! It suggests `/usr/lib/menhirLib`, which does not even exist.

However, `ocamlfind` can always return the correct location for Menhir, so maybe a defensive test can test for a faulty `--suggest-menhirLib` and fallback to `ocamlfind`?

**Comment by jhjourdan** [comment]
Cc @fpottier 

Could you please report this bug in Menhir's bugtracker (https://gitlab.inria.fr/fpottier/menhir/-/issues).

**Comment by xuanruiqi** [comment]
I can't create issues in the GitLab, so I have to wait for someone with access to GitLab to report this.

**Comment by fpottier** [comment]
Thanks for reporting this. If you are willing to depend on `ocamlfind`, then you should indeed use `ocamlfind query menhirLib`.

Menhir's `--suggest-menhirLib` dates back to the days when `ocamlfind` was not universally adopted. Its implementation today is not satisfactory (it makes a wild guess, which can be wrong). Maybe I should add a dependency of Menhir on `ocamlfind`, and re-implement `--suggest-menhirLib` to just call `ocamlfind query menhirLib`.

https://gitlab.inria.fr/fpottier/menhir/-/issues/42

**Comment by xavierleroy** [comment]
I fixed this in CompCert's configure script by calling `ocamlfind query menhirLib` first, and only if it fails, calling `menhir --suggest-menhirLib`.  

I agree the way `--suggest-menhirLib` is implemented in Menhir today is not satisfactory.  Earlier versions of Menhir tried harder to report the actual installation directory instead of guessing.

**Comment by tavianator** [comment]
This broke the build for me, since ocamlfind doesn't find menhir:

```
$ ocamlfind query menhirLib
ocamlfind: Package `menhirLib' not found
```

and the logic to fall back to `menhir --suggest-menhirLib` doesn't work because the exit status of a pipeline is that of the last command in it, which is a `tr` that succeeds even when `ocamlfind` fails:

```
$ ocamlfind query menhirLib
ocamlfind: Package `menhirLib' not found
$ echo $?
2
$ ocamlfind query menhirLib 2>/dev/null \
                           | tr -d '\r' | tr '\\' '/'
$ echo $?
0
```
