### ISSUE TITLE
opam coq-compcert (3.8) installs 64-bit version of clightgen

### ISSUE THREAD

**Issue by akinanop** [AbsInt/CompCert#384]
`opam install coq-compcert.3.7` installs a 32-bit version of `clightgen`, whereas `opam install coq-compcert.3.8` installs the 64-bit version. This creates incompatibilities for projects that use ASTs produced by `clightgen`.

**Comment by xavierleroy** [comment]
The coq-compcert OPAM packages are maintained by @MSoegtropIMC .

We (@MSoegtropIMC and I) agreed that x86 64 bits should be the default for these packages, as x86 32 bits is no longer supported by macOS and is on its way out in many Linux distributions.

There is a coq-compcert-32 OPAM package that you can install if you absolutely must work with x86 32 bits.

**Comment by MSoegtropIMC** [comment]
Actually a 3.8 32 bit opam package is not yet published, but it is available in the v8.13 branch of the Coq platform (https://github.com/coq/platform/tree/v8.13/opam/packages/coq-compcert-32/coq-compcert-32.3.8). The upstream merge was a bit delayed by the merge of a different opam package for 3.8 64 bit.

You might want to consider using the Coq Platform to setup your system.

I am currently in the process of making upstream PRs for the opam packages in Coq platform v8.13.

**Comment by MSoegtropIMC** [comment]
See (https://github.com/coq/opam-coq-archive/pull/1543) which adds a CompCert 32 bit opam file.

**Comment by MSoegtropIMC** [comment]
Doing the merge I saw that meanwhile there is an opam package for CompCert 32 bit. If you are on Windows you might still have to wait for the mentioned PR to be merged, because it enables to build 32 bit CompCert on 64 bit cygwin/MinGW).
