### ISSUE TITLE
opam coq-compcert 3.8 is broken due to an updated Menhir

### ISSUE THREAD

**Issue by davidnowak** [AbsInt/CompCert#393]
With Menhir 20210419, the following error occurs:

```
# OCAMLOPT cparser/Parse.ml
# File "cparser/Parse.ml", line 75, characters 13-49:
# 75 |            | Parser.MenhirLibParser.Inter.Fail_pr ->
#                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound constructor Parser.MenhirLibParser.Inter.Fail_pr
```
It works fine with Menhir 20210310.

**Comment by xavierleroy** [comment]
Yes, this is a known incompatibility introduced by the latest Menhir version.  Will be fixed in a future release of CompCert.  Right now we need to fix the OPAM package description for coq-compcert to exclude the latest Menhir, as discussed with @MSoegtropIMC recently.
