### ISSUE TITLE
how to compiler

### ISSUE THREAD

**Issue by WilliamWangPeng** [AbsInt/CompCert#397]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119221446-06a9b700-bb22-11eb-9035-231d0dc2ae1c.png)

thank you  
best regards to you  
William

**Comment by xavierleroy** [comment]
You will find detailed installation instructions in the user's manual: https://compcert.org/man/manual002.html

A short answer: install `opam`, then run
```
      opam switch create 4.12.0     # Use OCaml version 4.12.0 (for example)
      eval `opam env`
      opam install coq=8.12.2       # Use Coq version 8.12.2 (for example)
      opam install menhir
```
At this point you'll have an appropriate environment to build CompCert from sources.
