### ISSUE TITLE
Fatal error: out of memory.

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#4]
When compiling pf.c CompCert runs out of memory. Pre- and post-processed source here:
* http://dickman.org/compcert/2.4/test13/pf.c
* http://dickman.org/compcert/2.4/test13/pf.i

Console output:

    $ ccomp pf.i
    ../../../../sys/lock.h:47: Warning: empty struct.
    ../../../../net/pf.c:3045: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    ../../../../net/pf.c:3046: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    ../../../../net/pf.c:3050: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    ../../../../net/pf.c:3051: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    ../../../../net/pf.c:3056: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    ../../../../net/pf.c:3057: Warning: argument #2 of function call has type
      char * instead of the expected type u_int8_t const *.
    Fatal error: out of memory.

**Comment by xavierleroy** [comment]
Branch "named structs" merged by commit [master d594c5d].  This fixes the present issue.
