### ISSUE TITLE
Question of principles

### ISSUE THREAD

**Issue by throwaway1037** [AbsInt/CompCert#405]
Please may @m-schmidt explain why he closed #390 and #391, and he does not want to discuss license changes? I also do not appreciate the censorship from quickly shutting these issues down and preventing people from communicating via them.

For context, I believe in software freedom (see gnu.org and fsf.org), and this project does not respect the freedom of its users and as such is proprietary and unethical.

Switching to a known free license, even as a dual-licensed project, as is currently done for a subset of this project's files, would liberate the project and allow a lot of benefit to a lot of people; imagine compiling entire operating systems or packages with a proven compiler, for example.

All this potential good is locked behind the entirely preventable and curable decision to release this project under a proprietary license. This can be easily rectified, but it seems that @m-schmidt does not even want to discuss this at all. Is he afraid to admit his unethical practices and principles? Is he afraid to change for the better? Do his actions accurately represent the views of the rest of the contributors to this project?

I wish for a world in which we can all cooperate and respect the freedom of our neighbours. This project is actively hostile towards that goal, and I truly believe its leaders can make a positive change to benefit all of society and humanity as a whole. It would be a tremendous shame to spend a massive amount of time reimplementing a proven compiler as free software, just because CompCert is nonfree, and I really don't want to have to start a new project. I'd rather cooperate with this existing community and share my changes such that we can build something better together.

Thank you for reading.

**Comment by gek169** [comment]
This repository should be CC0.

**Comment by xavierleroy** [comment]
We  (the CompCert developers) agree on the current licensing of CompCert and would like this issue tracker to be used for technical issues only.  Therefore, your opinions on licenses do not belong here.  There are many other places where you can express them, so your use of the word "censorship" is not appropriate.

**Comment by throwaway1037** [comment]
Please may you at least explain why you will not release CompCert as libre software?

**Comment by xavierleroy** [comment]
@throwaway1037: Which part of "we would like this issue tracker to be used for technical issues only" didn't you understand?  You've been aggressive, disrespectful of the rules of this forum, and hiding behind a pseudonym.  There is no way I'll enter into a discussion with you.
