### ISSUE TITLE
duplicate semi-colon causes syntax error

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#41]
Is this syntax error expected?

```
$ cat foo.c
struct x {
        int a;;
};

int main(int argc, char **argv) {
        struct x foo;

        foo.a = 1;
        return foo.a;
}
$ ccomp foo.c
foo.c:2: syntax error: expecting '}'.
foo.c:1: this is the location of the unclosed '{'.
Fatal error; compilation aborted.
1 error detected.
```

When "int a;;" is replace with "int a;" the above works as expected. Here's with gcc:

```
$ gcc -std=c99 -pedantic foo.c
foo.c:2: warning: extra semicolon in struct or union specified
```

**Comment by xavierleroy** [comment]
Yes, this is expected.  According to ISO C99, section 6.7.2.1, a lone semicolon is not a "struct_declaration", because a "struct_declarator" and (therefore) a "struct_declarator_list" cannot be empty.

**Comment by didickman** [comment]
Thanks for the explanation. If possible, It would be nice to have a more specific error message.
