### ISSUE TITLE
Alignment verification in the builtin memcpy on aarch64

### ISSUE THREAD

**Issue by Yuki21** [AbsInt/CompCert#410]
On aarch, the builtin memcpy function, which generates asm in `Asmexpand`, does not check the alignment of load offsets (but for a ldr, the standard requires the offset to be a multiple of four/eight in 32/64 bits registers).

Below, an example which makes CompCert fail (the gcc assembly detects the error in the asm file generated by CompCert) : 
```C
struct a b;
struct a {
  short;
  int;
  short;
} c() {
  struct a d[2][16];
  b = d[1][7];
}
```

To fix this, one should add the corresponding check in `Asmexpand` (it works on our CompCert fork):

```diff
@@ -185,6 +185,7 @@ let memcpy_small_arg sz arg tmp =
  | BA_addrstack ofs ->
      if offset_in_range ofs
      && offset_in_range (Ptrofs.add ofs (Ptrofs.repr (Z.of_uint sz)))
+     && (Z.to_int ofs) mod 8 = 0
      then (XSP, ofs)
      else begin expand_addimm64 (RR1 tmp) XSP ofs; (RR1 tmp, _0) end
  | _ ->
```

**Comment by xavierleroy** [comment]
Well spotted, thanks for the report.

The rules for valid load-store offsets in ARMv8 are complicated (9 bit signed or 12 bit unsigned scaled by the transfer size, except for double-register operations where it's 7 bit signed and scaled), so there might be more complicated criteria (taking size and offset into account).  But the simple criterion "ofs mod 8 = 0" should work fine.
