### ISSUE TITLE
Informative: pick of tag for upcoming release of Coq Platform for Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [AbsInt/CompCert#414]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that your latest tag does work fine with Coq 8.14+rc1.

Coq Platform currently uses the opam package 'coq-compcert.3.9~flex'
from platform patch repository https://github.com/coq/platform/tree/main/opam/opam-coq-archive/extra-dev.

__Note:__ We had to patch the opam package and possibly the make file to accept the new version of Coq, but no other changes were required.

In case this is the version you want to see in Coq Platform, there is nothing to do for you - just close this issue.

In case you would prefer to see an updated version in the upcoming Coq Platform, please inform as as soon as possible!

Thanks!

P.S.: this issue has been created semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by xavierleroy** [comment]
Sounds good to me.  CompCert will have a release by the end of this year, but VST needs work to adapt to recent CompCert changes.  This work is in progress, but it might be wiser to stick with CompCert 3.9 and the current VST for the Coq platform 8.14.0 release.

**Comment by xavierleroy** [comment]
PS.  Thanks for the personalized heads-up !

**Comment by MSoegtropIMC** [comment]
Thanks for the confirmation and further timeline information! Shall I go ahead and change the CompCert 3.9 opam package to allow Coq 8.14 (it currently doesn't)?

**Comment by xavierleroy** [comment]
> Shall I go ahead and change the CompCert 3.9 opam package to allow Coq 8.14 (it currently doesn't)?

If it builds correctly with 8.14, yes.  I tried to build with Coq 8.14 rc1 and got errors with the vendored Menhirlib:

> File "./MenhirLib/Alphabet.v", line 14, characters 24-29:
> Error: Unable to locate library Omega with prefix Coq.

Maybe your non-vendored Menhirlib was fixed already.  Right now I don't have time to investigate which incompatible changes were made in Coq 8.14.  If you can provide more info, it will be much appreciated.

Cc: @jhjourdan for Menhirlib.

**Comment by MSoegtropIMC** [comment]
Yes, CompCert 3.9 (and VST 2.8) build fine with Coq 8.14+rc1 in the Coq Platform context.

I am using these versions of CompCert dependencies:
```
coq-menhirlib.20210419 menhir.20210419
coq-flocq.3.4.2
```
Omega has been deprecated in 8.14, so anything using Omega won't work with 8.14 any more. In the opam files of coq-menhirlib versions which use omega, one might want to put an upper bound for the Coq version.

**Comment by xavierleroy** [comment]
FYI: CompCert 3.10 was released today, but I'm still OK with having 3.09 in the November Coq platform.

**Comment by MSoegtropIMC** [comment]
Thank you for the information! Andrew is apparently close before releasing a compatible VST version. May I come back to you early next week for a final decision?
