### ISSUE TITLE
static functions possible bug

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#42]
CompCert seems to have a difference in behaviour from gcc when either the prototype or the function definition is declared static, but not both. Here's an example with foo.c and bar.c:

```
# cat foo.c
static int foo(void);

int foo(void) {
        return 1;
}
# cat bar.c
int foo(void);

static int foo(void) {
        return 1;
}
# gcc -c foo.c
# gcc -c bar.c
bar.c:3: error: static declaration of 'foo' follows non-static declaration
bar.c:1: error: previous declaration of 'foo' was here
# ccomp -fall -c foo.c
foo.c:3: Warning: redefinition of 'foo' with incompatible storage class.
# ccomp -fall -c bar.c
bar.c:3: Warning: redefinition of 'foo' with incompatible storage class.
```

I believe CompCert should not show a warning with foo.c and should fail to compile bar.c as gcc does. Here's a stackoverflow link where someone references the C standard:

http://stackoverflow.com/questions/15670010/does-a-static-function-need-the-static-keyword-for-the-prototype-in-c

**Comment by didickman** [comment]
And here is with clang for completeness:

```
# clang -std=c99 -pedantic -c foo.c
# clang -std=c99 -pedantic -c bar.c
bar.c:3:12: error: static declaration of 'foo' follows non-static declaration
static int foo(void) {
           ^
bar.c:1:5: note: previous declaration is here
int foo(void);
    ^
1 error generated.
```

**Comment by bschommer** [comment]
The behavior you describe is actually the desired one. Commit ad613e10f78bfe11e2df2ec055bcd02406456476 should fix this.

**Comment by didickman** [comment]
fixes things for me. thanks.
