### ISSUE TITLE
x86 execution semantics quirk

### ISSUE THREAD

**Issue by xxuejie** [AbsInt/CompCert#432]
Hi there,

I was recently trying to leverage CompCert's execution semantics to prove the equivalence of same programs written in 2 assembly languages(I know this is NOT a convential use case for CompCert, but CompCert already provides formal semantics for multiple architectures, so why not :P). So I put together a dummy code snippet trying to have CompCert **execute** an x86_64 instruction:

```
Definition i : instruction := Pmovq_rm RDI (Addrmode (Some RCX) None (inl _ 0)).
Definition m : mem := Mem.empty.
Definition r : regset := Pregmap.init (Vint (Int.repr 0)).
Definition f : function := mkfunction signature_main nil.
Definition g : genv := Genv.empty_genv Asm.fundef unit nil.

Compute (exec_instr g f i r m).
```

This snippet would run into `Stuck` phase. While I was diving into CompCert's code, I noticed something that is quite strange to me:

* The executed code starts from [here](https://github.com/AbsInt/CompCert/blob/318fc06823eb577e9b386aeea57133e8c3938ecf/x86/Asm.v#L622-L623)
* `exec_load` first invokes `eval_addrmode`, landing at [here](https://github.com/AbsInt/CompCert/blob/318fc06823eb577e9b386aeea57133e8c3938ecf/x86/Asm.v#L400-L416) for 64 bit mode, one thing we can learn from the code, is that unless a symbol is provided, the value returned from `eval_addrmode64` will always be a `Vlong` instead of a `Vptr`.
* Back to `exec_load`, it tries to call `Mem.loadv`, however, [Mem.loadv](https://github.com/AbsInt/CompCert/blob/318fc06823eb577e9b386aeea57133e8c3938ecf/common/Memory.v#L443-L447) would only accept a val of `Vptr`, for vals of `Vlong`, it would immediately return `None`, triggering later logic in to return a `Stuck` state.

If the above deduction is correct, when executing `Pmovq_rm`, `exec_instr` would only handle the case that an actual symbol is provided, and will always result in a `Stuck` state otherwise. For example, when we have a `mov` instruction that tries to load the memory based on values in a register.

So my question here is: is this correct behavior of CompCert's execution semantics now? Or am I missing something here?

**Comment by xavierleroy** [comment]
As is the case for all CompCert intermediate languages, the x86-64 assembly semantics uses the CompCert memory model described in [this technical report](https://hal.inria.fr/hal-00703441) and also in the book [Program Logics for Certified Compilers](https://vst.cs.princeton.edu/veric/).

In this model, an integer (`Vint` or `Vlong` in CompCert) is **never** a valid memory address.  Memory addresses must be of the form `Vptr block offset`, where `block` is a block identifier and `offset` a byte offset within this block.  

Valid pointers can be obtained from global symbol addresses, as you noted, but also from the stack pointer and from the result of the built-in `malloc` function.

In your example, `RCX` contains the integer zero, if I'm not mistaken, so you cannot use it as the address of a load (the `movq_rm` instruction), execution gets stuck if you do.  You're dereferencing the null pointer, actually...

Let me know if it doesn't answer your question.

**Comment by xxuejie** [comment]
@xavierleroy Thank you for your detailed answer!

> In your example, RCX contains the integer zero, if I'm not mistaken, so you cannot use it as the address of a load (the movq_rm instruction), execution gets stuck if you do. You're dereferencing the null pointer, actually...

Yes it appears to be dereferencing a null pointer but the real problem here is that I've simplified too much in the example :) The real code I want to prove lies [here](https://github.com/nervosnetwork/ckb-vm/blob/3d50ec6e419c66311708b093b991d94bfac987a5/src/machine/asm/execute_x64.S#L375), which contains loads from addresses stored in registers other than `rsp`. In this case, I'm using `rsi` and `rdx`. And there might be more other registers used here.

Since the code I'm using here is written purely in assembly, they won't be from global symbol addresses, nor do they have anything to do with malloc. So judging from the CompCert memory model, there is no way I can turn values stored in a plain register such as `rsi` into a valid memory address, correct?

And to make the background more complete, I do want to admit that this is a very weird use case for CompCert's execution semantics, [sail](https://github.com/rems-project/sail) would suit my goal better. The reason I'm trying CompCert here, is that CompCert is the only project I know of, that contains both execution semantics for RISC-V and x86_64 architectures. While sail does cover RISC-V and aarch64, the x86 model contained in sail is obsolete at the moment.

**Comment by xavierleroy** [comment]
I'm not going to read your asm code, but unless you run on bare metal, it's quite likely that the memory it accesses comes from global variables or malloc or sbrk or some other facility that gives you base pointers from which the asm code can derive other pointers.

At any rate, CompCert's Asm semantics are for assembly languages with a relatively high-level memory model.  If you're looking for machine-language semantics where memory is just a big array of bytes, it's not going to help, indeed.  The CakeML compiler goes all the way down to machine language, if I remember correctly, so you might find interesting machine-language semantics in there: https://github.com/CakeML .

**Comment by xxuejie** [comment]
> I'm not going to read your asm code

Totally understandable!

> but unless you run on bare metal, it's quite likely that the memory it accesses comes from global variables or malloc or sbrk or some other facility that gives you base pointers from which the asm code can derive other pointers.

Well here's the quirk: while we do have some conventions maintained in the assembly like following:

* `r8` keeps the current `PC` of the interpreted RISC-V virtual machine
* `rdx` keeps track of register `rs1` in a R-typed RISC-V instruction
* `rsi` keeps track of the `Machine` struct for the overall RISC-V virtual machine

In reality, those conventions are all maintained in pure x86/aarch64 assembly code, hence there is no global variables or malloc or sbrk attached to them.

It does sound like I might need to look for a relatively lower level machine language semantics than what's used in CompCert now, I will definitely take a look at CakeML. Thank you very much for all your explanation and advice!
