### ISSUE TITLE
Switch.v  out-of-sync documentation 

### ISSUE THREAD

**Issue by fajb** [AbsInt/CompCert#435]
It seems that the documentation of Switch.v is out-of-date.
It states that jumptables are generated by RTLgenaux.ml.
Since 17f519651feb4a09aa90c89c949469e8a5ab0e88, it is done at instruction selection.

**Comment by fajb** [comment]
PS: This is just for the record. No need to keep it open.

**Comment by xavierleroy** [comment]
Hey, don't close, otherwise I'll never get to fix the comment :-)
