### ISSUE TITLE
CompCert 3.11 builds but then fails with Flocq 4.0

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#438]
I downloaded the .tar.gz file for the 3.11 release of CompCert,
configured it as usual with
`./configure x86_32-cygwin -use-external-Flocq -clightgen
`
and then did "make -kj7" as usual.  The make completed without error.
However, when I try to run either clightgen or ccomp, I get the following error:
`Fatal error: exception Failure("AXIOM TO BE REALIZED")
`
This happens even if the .c file is empty, or simply contains` int f(int x) {return x;} `.
It happens if I simply try `clightgen --version`.
It happens the same way if I configure with x86_64.

**Comment by andrew-appel** [comment]
Yes, it works without `-use-external-Flocq`.   I presume it will work in Coq Platform 2022.04.1 -- I will report back.  Meanwhile, I will rename this issue, since it's not about cygwin.

**Comment by xavierleroy** [comment]
I'm not quite sure how to check Flocq's version from a shell script.  (From a Coq file it's easy.)  At a minimum, CompCert could check for axioms not realized at extraction time.
