### ISSUE TITLE
.global directive not recognized in MacOS X Yosemite

### ISSUE THREAD

**Issue by xavierleroy** [AbsInt/CompCert#44]
A user reports an assembler error on MacOS X Yosemite:

../../ccomp -stdlib ../../runtime -dparse -dc -dclight -dasm -fall -o int32.compcert int32.c 
[...]
int32.s:562:Unknown pseudo-op: .global
int32.s:562:Rest of line ignored. 1st junk character valued 95 (_).
Error during assembling.

It works with ".globl" instead of ".global".  See: http://stackoverflow.com/questions/10512248/unknown-pseudo-op-global

**Comment by bschommer** [comment]
The problem is the version of the gnu assembler used. Under MacOS X Yosemite it is 1.38.

**Comment by xavierleroy** [comment]
A simple solution would be to use ".globl" instead of ".global" for all the targets supported by CompCert.  Both the  GNU assembler and the Diab C assembler support ".globl" as an alias for ".global".

**Comment by bschommer** [comment]
This was already done for functions but not for variables. Commit 56bac3dc3d45c219db5d9c7b6a97794c00f8115e should fix this.
