### ISSUE TITLE
Erroneous bit field dwarf info leading to bit overlay (or union) in debugger

### ISSUE THREAD

**Issue by elfman2** [AbsInt/CompCert#445]
ccomp v3.11, v3.10, aarch64, -g3 -gdwarf-3:

```
typedef struct tt{
  int i1:8;
  int i2:8;
  int i3:8;
  int i4:8;
}tt;
tt t;
```

(gdb) p t
$1 = {i1 = 0, i2 = 0, i3 = 0, i4 = 0}
(gdb) set t.i1=1
(gdb) p t
$2 = {i1 = 1, i2 = 1, i3 = 1, i4 = 1}

**Comment by xavierleroy** [comment]
Well spotted, thanks for the report.  The handling  of bitfields changed in 3.10 and  debugger support was not updated.  Fixed in 9fcb0316d by @bschommer .
