### ISSUE TITLE
CompCert ARM32 uses IR12 as frame pointer?

### ISSUE THREAD

**Issue by shenghaoyuan** [AbsInt/CompCert#455]
Hello,
     In general, ARM32 uses IR11 as the frame pointer register (i.e. FP) [1], but CompCert currently is using IR12 as FP.
     Considering the [following implementation](https://github.com/AbsInt/CompCert/blob/master/arm/Asm.v#L760),

```coq
  | Pallocframe sz pos =>
      let (m1, stk) := Mem.alloc m 0 sz in
      let sp := (Vptr stk Ptrofs.zero) in
      match Mem.storev Mint32 m1 (Val.offset_ptr sp pos) rs#IR13 with
      | None => Stuck
      | Some m2 => Next (nextinstr (rs #IR12 <- (rs#IR13) #IR13 <- sp)) m2
      end
```
CompCert generates assembly code like (see [Asmexpand.ml](https://github.com/AbsInt/CompCert/blob/master/arm/Asmexpand.ml#L577)):

```shell
        mov     r12, sp
        sub     sp, sp, #sz
        str     r12, [sp, #pos]
```
Are there any special reasons to select IR12 instead of IR11 as FP for CompCert? (because IR11 is callee-save?)
If so, btw, the [comment](https://github.com/AbsInt/CompCert/blob/master/arm/Asm.v#L288) should be r12 instead of r10

[1] https://developer.arm.com/documentation/100067/0607/armclang-Command-line-Options/-fomit-frame-pointer---fno-omit-frame-pointer

**Comment by xavierleroy** [comment]
CompCert does not use a frame pointer to access the stack frame of the current function: all accesses are relative to SP, the stack pointer.  In turn, the register that is reserved for the frame pointer in the ABI can be used like any other callee-save register.  This is useful for architectures that don't have many registers, such as x86 and ARM.

More generally, frame pointers are useless when stack frames have fixed (known at compile-time) sizes and layout, which is  always the case in CompCert (`alloca` and variable-length arrays are not supported).

However, to match the correctness proof and the formal memory model, each stack frame must contain a pointer to the frame of the caller function.  Hence, the function prologue contains instructions that save the caller's SP to a temporary register (here, R12), decrements SP (to allocate the new stack frame), and stores the temporary in the new stack frame.  It looks a bit like the sequence that would set up and maintain a traditional frame pointer, but the main difference here  is that R12 is used temporarily in the function prologue, but not maintained throughout the function body.  Indeed, R12 can be used as a temporary or a caller-save register later in the function.

I hope this answers the question.

**Comment by shenghaoyuan** [comment]
Hello,
       It solves my question~
       Thanks a lot!
