### ISSUE TITLE
switch3 test takes forever

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#462]
rev abe1f24dfb2b1b67dfeeaf3513e6d3d534f7df32

```
./configure arm-eabihf --toolprefix arm-linux-gnueabihf- && make -j8 && make -C test SIMU='qemu-arm -L /usr/arm-linux-gnueabihf' all test|tee test.log
```

All goes well until the `switch3` test, which seems to loop forever.

**Comment by xavierleroy** [comment]
That was a noob error in writing the test.  It happened to work if `char` is signed...  Should be fixed in d3edf6c.
