### ISSUE TITLE
armv7r and default thumb mode

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#463]
The documentation says
```
-mthumb
This option applies only to the ARM port of CompCert. It instructs CompCert to generate code
using the Thumb2 instruction encoding. This is the default if CompCert was configured for the
ARMv7R profile.
```
Yet when I configure CompCert using `/configure armv7r-eabihf --toolprefix arm-linux-gnueabihf-` it still seems to produce `.arm` code by default.

**Comment by m-schmidt** [comment]
This is a bug in the manual. The correct text should be:

    This is the default if CompCert was configured for the ARMv7M profile.

 We fixed this a few month ago for the man-page, but missed the manual. I just updated the manual sources. The fix should be contained in the next public release.
