### ISSUE TITLE
encoding of load immediate in ARM Thumb2 mode

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#464]
Comments in `arm/TargetPrinter.ml` imply that encoding of `mov`with an immediate operand is shorter as `mov` than `movs`. Yet, this does not seem to be the case (checked with `objdump`): `movs r0, #1` is encoded as 0x2001, whereas `mov r0, #1` is encoded as 0xf04f 0x0001.

I suggest investigating using `movs` in appropriate cases.

**Comment by xavierleroy** [comment]
AbsInt has been looking into more compact Thumb code recently, and this is one of their improvements.  See commit 431b64db9 .
