### ISSUE TITLE
internal error in the front-end when compiling certain structure constructs

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#471]
```
struct b {
  int *a;
};
struct {
  struct b *c;
} d = {&(struct b){&(int){2}}};
```

ccomp prints out
```
ccomp: error: internal error: rename: __compound__77 unbound
```

**Comment by m-schmidt** [comment]
The problem is probably in `Unblock.ml`, function `unblock_decl`.

During `expand_init` global variables are collected in `global_variables` for compound initalizers. Since the initializer in the example is nested, two compounds were created, but are in the wrong order.

Potential fix:

````
    let decls = List.rev !global_variables in
````

**Comment by m-schmidt** [comment]
A similar code pattern is used for `local_variables` in `unblock_fundef`.
