### ISSUE TITLE
bad definition/use of variable error message

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#479]
The following program is a reduced version of some Dhrystone-kind of code in K&R C:
```
int a() { return b(0); }
inline int b(c) double c;
{ return (c + 2.0); }
```

CompCert terminates with a mysterious error message
```
$ ccomp -dall -S inlineuntyped2.c
inlineuntyped2.c:1: warning: implicit declaration of function 'b' is invalid in C99 [-Wimplicit-function-declaration]
inlineuntyped2.c: error: In function a: At PC 3: bad definition/use of variable 4
1 error detected.
```

I agree this code is ill-typed, and has undefined behavior, but some users may be puzzled by the error message.

**Comment by xavierleroy** [comment]
I don't think we can give a better error message, since the type discrepancy is detected quite late in the compiler.  One more reason to ban K&R function definitions entirely.

**Comment by monniaux** [comment]
A similar result can be achieved using casts on function pointers and calling the inlining pass after constant propagation.

I wonder if it could be possible to modify RTL typing error messages by adding e.g. "This problem most likely comes from wrongly typed programs (K&R old-style functions wrongly used, incorrect function pointer casts…) undergoing inlining.", so that the user may have an idea of what's going on and would be inclined to look into the code instead of blaming the compiler.
