### ISSUE TITLE
VERSION file still in 3.12

### ISSUE THREAD

**Issue by maroneze** [AbsInt/CompCert#497]
This is a very minor remark: the commit currently tagged as `v3.13` (920da14e4) still has its `VERSION` file containing `3.12`, so when compiled from source,`ccomp --version` still outputs 3.12.

**Comment by xavierleroy** [comment]
Ah, this is not the first time this happens... Will fix tomorrow.  Thanks for the report!

**Comment by xavierleroy** [comment]
OK, this should now be fixed on the 3.13 bug-fix branch (https://github.com/AbsInt/CompCert/tree/3.13) from which I cut a 3.13.1 bug-fix release which you can get through https://github.com/AbsInt/CompCert/releases/tag/v3.13.1 or via git with tag v3.13.1.  Let me know if you see anything wrong.
