### ISSUE TITLE
Old documentation?

### ISSUE THREAD

**Issue by alxest** [AbsInt/CompCert#50]
In https://github.com/AbsInt/CompCert/blob/master/backend/RTL.v#L110, it mentions [fn_code_wf], and [fn_nextpc]. However, I cannot find [fn_code_wf]'s definition or usage. (I've greped whole repository)

**Comment by xavierleroy** [comment]
You're correct, the comment is outdated.  Will fix it soon.  Thanks for the report.

**Comment by xavierleroy** [comment]
Fixed, but not really "soon", by commit [master d354260]
