### ISSUE TITLE
How to generate 32 bit binary with 64 bit version CompCert?

### ISSUE THREAD

**Issue by Luweicai** [AbsInt/CompCert#504]
Hi, I am a new to CompCert.
How to generate the 32 bit binary with a 64 bit version CompCert? I build a x86_64-linux version CompCert in Ubuntu 20.04.
I use the ini file with the following configure file
```
stdlib_path=/usr/local/lib/compcert
prepro=gcc
linker=gcc
asm=gcc
prepro_options=-m32 -U__GNUC__ -E
asm_options=-m32 -c
linker_options=-m32 -no-pie
arch=x86
model=32sse2
abi=standard
endianness=little
system=linux
has_runtime_lib=true
has_standard_headers=true
asm_supports_cfi=true
response_file_style=gnu
``` 
But it does not work with the error:
```
...
/tmp/compcertc1c8c6.s:1376: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1378: Error: bad register name `%rsp)'
/tmp/compcertc1c8c6.s:1379: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1382: Error: bad register name `%rdi'
/tmp/compcertc1c8c6.s:1383: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1385: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1395: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1397: Error: bad register name `%rsp)'
/tmp/compcertc1c8c6.s:1398: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1401: Error: bad register name `%rdi'
/tmp/compcertc1c8c6.s:1402: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1404: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1414: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1416: Error: bad register name `%rsp)'
/tmp/compcertc1c8c6.s:1417: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1420: Error: bad register name `%rdi'
/tmp/compcertc1c8c6.s:1421: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1423: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1433: Error: bad register name `%rsp'
/tmp/compcertc1c8c6.s:1435: Error: bad register name `%rsp)'
/tmp/compcertc1c8c6.s:1436: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1439: Error: bad register name `%rdi'
/tmp/compcertc1c8c6.s:1440: Error: bad register name `%rax'
/tmp/compcertc1c8c6.s:1442: Error: bad register name `%rsp'
ccomp: error: assembler command failed with exit code 1 (use -v to see invocation)

```
I might write the wrong ini file, how does the right one looks like?

**Comment by xavierleroy** [comment]
Maybe you did not update the Makefile.config file.  Both compcert.ini and Makefile.config are generated by the configure script, you don't have to write them yourself.  Just do
```
make clean
./configure x86_32-linux
make
```
and it should work.

**Comment by Luweicai** [comment]
Hi, I might not describe my problem correctly.
I do not want to generate the 32 bit compcert, I want to use 64 bit compcert to compile a program into 32 bit form. (Is that possible?)

**Comment by xavierleroy** [comment]
> I do not want to generate the 32 bit compcert, I want to use 64 bit compcert to compile a program into 32 bit form. (Is that possible?)

For x86, no, it's not possible, the differences between 32-bit and 64-bit code are too large, so some of them are "hard-wired" in the ccomp executable.

AFAIK, RISC-V is the only target where 32-bit and 64-bit modes are supported by the same ccomp executable and could therefore be selected just by changing the compcert.ini file.

**Comment by Luweicai** [comment]
Thank you for your reply!
