### ISSUE TITLE
Please pick the version you prefer for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [AbsInt/CompCert#505]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.18.0`.

Coq Platform CI is currently testing opam package `coq-compcert.3.13.1`
from platform patch repository https://github.com/coq/platform/tree/main/opam/opam-coq-archive/released/packages/coq-compcert/coq-compcert.3.13.1/opam.  **This means we had to weaken some version restrictions in the opam package, but no other changes were required.**

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2023.10`, please inform us as soon as possible and before **October 31st, 2023**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by andrew-appel** [comment]
And also:  Please inform me which version of CompCert will be in  that Coq Platform release, so I can make sure VST is compatible.  For the time being I will assume CompCert 3.13.1.

**Comment by andrew-appel** [comment]
In fact, if someone could advise me where, if anywhere, there is an opam package of coq-compcert and coq-compcert-32 for Coq 8.18.0, then I could properly configure VST's own CI for coq 8.18.   I tried to do it with 
```
opam install --ignore-constraints-on=coq-compcert,coq-compcert-32 -y coq-compcert.3.13
```
but I cannot get this --ignore-constraints-on feature to work.  (I am not very expert at using opam.)

**Comment by xavierleroy** [comment]
OK for version 3.13.1.  I'm not planning to release a newer version of CompCert by November 2023.  Version 3.13.1 builds OK with Coq 8.18, albeit with many warnings.  Thanks!
