### ISSUE TITLE
Question on the Enforcability of copyright based license restrictions on usage in github.

### ISSUE THREAD

**Issue by jmikedupont2** [AbsInt/CompCert#507]
First of all I am not a lawyer or a troll, this is a good faith attempt to comprehend the law and follow the license, but also the law, and the github terms of service. I have personally researched into this particualar question for over 20 years now with the gcc itself. I respect your work and your license but I take issue with the idea that somehow you can restrict the "USAGE" of some software that is published on github.

"""3. Limitations on Use: The License is limited to noncommercial
   use. Noncommercial use relates only to educational, research,
   personal or evaluation purposes. Any other use is commercial use.
   You may not use the Software in connection with any activities   which purpose is to procure a commercial gain to you or others.""" 

How is the even enforcable for some file i got from github? 
How did i agree to this license?
How is the usage restricted on my computer what I do ? 
If I run this code to extract coq statements about software that is open source, how are you asserting any ownership over mechanical compilation and reformatting of data that is already present in my code? 

This is my understanding, I am not a lawyer, would like to have clarification, we can ask the software freedom law center or others for help.

Under github rules anyone can  change the code as they can  change the format or circumvent your restrictions. There is no way to legally restrict usage of software on github running on my personal pc. You would need a EULA, there is no agreement or license that has taken place except for me to download your files from github. That does not constitute an agreement to any of your terms. 
The GPL is enforcable because it restricts the distribution of same code , so redistributing your code would trigger a copyright violation.

Redistribute of derived works of my code that used your code to generate some transformations of it are not covered or restricted by your licenses. 

Please realize that I have been through this thought process many time concerning the restricting of the gcc plugins as well, and there is no way for them to restrict the usage of the gcc internals either via copyleft. I have spent over 20 years thinking and reasearching about this issue since I started my quest to extract ast information from the gcc in my ongoing gcc rdf introspector project that has recently been rebooted due to the advent of the llm

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Note: If you publish your source code in a public repository on GitHub, according to the Terms of Service, other users of GitHub.com have the right to view and fork your repository. If you have already created a repository and no longer want users to have access to the repository, you can make the repository private. When you change the visibility of a repository to private, existing forks or local copies created by other users will still exist. For more information, see "Setting repository visibility."

Looking forward to a quick resolution,
mike

**Comment by m-schmidt** [comment]
I'm closing this issue here. We answered your parallel mail on this topic. Feel free to contact INRIA France directly.

**Comment by jmikedupont2** [comment]
This is a public project on github and I think the public might expect to have an answer in public?
