### ISSUE TITLE
Please pick the version you prefer for Coq 8.19 in Coq Platform 2024.01

### ISSUE THREAD

**Issue by rtetley** [AbsInt/CompCert#511]
The Coq team released Coq `8.19.0` on January 24th, 2024.
The corresponding Coq Platform release `2024.01` should be released before **April 30th, 2024**.
It can be delayed in case of difficulties until May 15th, 2024, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.19.0`.

Coq Platform CI is currently testing opam package `coq-compcert.3.13.1`
from official repository https://coq.inria.fr/opam/released/packages/coq-compcert/coq-compcert.3.13.1/opam. 

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2024.01`, please inform us as soon as possible and before **March 31st, 2024**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.19~2024.01+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.19~2024.01+beta1.sh) which already supports Coq version `8.19.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/405

**Comment by xavierleroy** [comment]
OK for using CompCert 3.13.1.  I'm not planning another release of CompCert before this summer.  Thanks for your work on the Platform!
