### ISSUE TITLE
Impossible to link ccomp object files with MSYS2 MinGW64

### ISSUE THREAD

**Issue by NikNik77771** [AbsInt/CompCert#517]
I am not sure that ccomp supports MinGW.

**Comment by xavierleroy** [comment]
Indeed, the public version of CompCert (from this repository) doesn't support MinGW, owing to incompatibilities with MinGW's standard C library and headers.  As mentioned in the user's manual, the only choice for running this version under Windows are Cygwin and WSL2.

The commercial version of CompCert distributed by AbsInt is based on MinGW + a different standard library, if I remember correctly.  You can contact [info@absint.com](mailto:info@absint.com) for more information.
