### ISSUE TITLE
opam install coq-compcert=3.13 installs VERSON 3.12

### ISSUE THREAD

**Issue by swarnpriya** [AbsInt/CompCert#522]
Hello,
For a project, I'm trying to install `coq-compcert` version `3.13`. However, when I install it through opam, it installs `3.12` or the version number is not updated correctly.

**Comment by xavierleroy** [comment]
Right, the version number was not updated in release 3.13.  This was fixed by release 3.13.1.  You can  `opam install coq-compcert=3.13.1` if you prefer.
