### ISSUE TITLE
make && make documentation does not work (fix proposed)

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#533]
rev 6da35478756dd895a1603e835f71cd7a6439f637

```
make
make documentation
```

results in
```
Fatal error: exception Sys_error("export/*.glob: No such file or directory")
make: *** [Makefile:263: documentation] Error 2
```

proposed fix
https://github.com/AbsInt/CompCert/pull/532

**Comment by xavierleroy** [comment]
Well spotted, thanks for the report.  Should be fixed by aee355d373181467aa40a306cd650992985c2c46 .
