### ISSUE TITLE
Clarification about va_arg with composite types

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#63]
I don't know if this is just a matter of updating the user manual, or if I misunderstood its meaning: section 7.15 says that the `va_arg` macro cannot fetch composite types, and that a compile-time error is generated if one tries to do so. I tried the following code in IA-32 Linux and it does compile with CompCert 2.4 and 2.5:

```
#include <stdio.h>
#include <stdarg.h>

typedef struct { int v; float f; } pair;
typedef union { char s[4]; int i; } variant;

void printer (int n, ...) {
  va_list argp;
  va_start(argp, n);
  pair p = va_arg(argp, pair);
  printf("pair = %d, %f\n", p.v, p.f);
  variant v1 = va_arg(argp, variant);
  printf("variant(s) = %s\n", v1.s);
  variant v2 = va_arg(argp, variant);
  printf("variant(i) = %d\n", v2.i);
  va_end(argp);
}

int main() {
  pair p = {42, 3.14};
  variant v1 = {.s = "abc"};
  variant v2 = {.i = 13};
  printer(3, p, v1, v2);
  return 0;
}
```

When run, it produces nonsensical results by default (like #20), but activating `-fstruct-return` makes it work without issues (again, like #20). So it seems to me that it is just a matter of updating the user manual.

**Comment by xavierleroy** [comment]
Indeed, the manual needs updating on this point.  It should be the case that with -fstruct-return activated, arguments of struct/union types can safely be retrieved using va_arg.  Do keep in mind, however,  that you're combining two features of C that lie outside of CompCert's formal proof (struct passing and vararg functions); I would advise against that in critical code.

**Comment by thranur** [comment]
Also, just to keep the remarks about the manual together in the same issue:

The "Using the CompCert C compiler" chapter mentions, for options `-fstruct-return` and `-fstruct-passing`, that:

> By default, CompCert chooses a calling convention appropriate for the ABI of the target platform.

That, and the fact that `-fstruct-return` without arguments is presented much earlier in the chapter (without a symmetric `-fstruct-passing` without arguments) are what got me confused. I'm not sure making the options symmetric would be very useful, however.

Anyway, thanks for the explanation and the reminder about the formal proof.
