### ISSUE TITLE
CompCert manual versioning and availability

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#64]
I couldn't find the CompCert user manual (http://compcert.inria.fr/man/) on Github, neither on the .tgz archives. There's the 2.4 release on HAL (https://hal.inria.fr/hal-01091802) and the latest one (currently 2.5) on the website, but is there an archive where older versions could be found? For instance, like OCaml's documentation which has the standard URL pointing to the latest release and alternative URLs pointing to fixed versions. This is mainly for future referencing purposes.

**Comment by xavierleroy** [comment]
Older versions of the user's manual are available at http://compcert.inria.fr/man-X.Y/  where "X.Y" is the version number, e.g. "2.4".  Those URLs should remain stable in the foreseeable future.

Speaking of future referencing purposes, do keep in mind that long-term support is provided for AbsInt's commercial version of CompCert, which also comes with documentation, but not for the evaluation & research version from compcert.inria.fr.
