### ISSUE TITLE
Loop unrolling

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#66]
After searching a bit, I didn't find any proven implementations of loop unrolling in CompCert.

Are there any such implementations that you are aware of? Otherwise, is it too complicated to be done (say, in a few days)?

If there are none, I'd like to try doing it, but I'm afraid it has already been tried and the proof would require several days/weeks of extensive work. I'd wager it's not complex enough to justify an article, but not simple enough to be done "for fun".

It seems that RTLgen would be the best place to do it, but defining the measure over CminorSel states with unrolling seems complicated.

**Comment by xavierleroy** [comment]
You are correct that CompCert performs no loop optimizations currently.  (As documented in section 1,3 of the reference manual.)  There were some ideas in the past to combine the polyhedral model of loop optimizations with validation a posteriori, see https://hal.inria.fr/hal-00655485.  For another approach also based on validation a posteriori, see http://doi.acm.org/10.1145/1993498.1993533 .  These two directions were not actively pursued, as far as I know.

I'd be happy to continue this discussion by e-mail at xavier.leroy AT inria.fr.
