### ISSUE TITLE
Initialisation of wchar_t arrays

### ISSUE THREAD

**Issue by rhymoid** [AbsInt/CompCert#71]
With CompCert 2.5, I've found that

    wchar_t const abc[] = L"abc";

is somehow treated as

    wchar_t const abc[] = { L'\0', L'a', L'b', L'c', L'\0' };

Meanwhile, `wchar_t const *abc = L"abc"` works as expected. I'm aware that wide character support is still a work in progress (#26), but this specific problem looks like it *might* point to some deeper issues.

**Comment by xavierleroy** [comment]
Even if wide char support in CompCert is rudimentary, this is clearly an implementation bug!  I'll fix this ASAP.  Thanks for reporting it.

**Comment by xavierleroy** [comment]
Fixed in commit [master 9f0fcc2].
