### ISSUE TITLE
Parsing or lexing duplicates return statements.

### ISSUE THREAD

**Issue by atrieu** [AbsInt/CompCert#72]
```C
$ menhir --version
menhir, version 20151112
$ cat test.c

int main(void) {
	return 100;
}

$ ./ccomp -dparse test.c
$ cat test.parsed.c

extern void __builtin_debug(int kind, ...);

int main(void)
{
  return 100;
  return 0;
}
```

I guess a bug was introduced with the recent changes in the lexer/parser as it does not happen with CompCert 2.5. The produced assembly code is not affected as the duplicate return is most likely removed during the optimizations (deadcode removal ?).

**Comment by bschommer** [comment]
This is actually no bug. The additional return 0 is introduced to ensure that main always returns 0 if no  explicit return is encountered before the end of main which is requires since CompCert compiles for a hosted environment. See §5.1.2.2.3 of the C standard.

**Comment by atrieu** [comment]
Oh okay, never mind then, but I still find it odd that this behaviour did not happen in 2.5 nor 2.4 but happens with trunk.
