### ISSUE TITLE
Makefile.menhir has bug when ocamlfind not present

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#81]
In the CompCert 2.6 distribution, "Note 2" seems to be inaccurate.

It says, 'If Menhir answers "-package menhirLib", then Menhir was installed with ocamlfind...'
But in fact, I installed my menhir-20151112 without ocamlfind, without opam,
and yet when I run
 menhir --table --suggest-comp-flags
the response is
-package menhirLib
which contradicts the sentence in the Makefile.menhir.

You might wonder why I installed menhir this way; well, I'm using a shared Linux server on which I don't have root privileges.

So I had to fix the problem by editing Makefile.menhir to set the MENHIR_INCLUDES to 
the particular path on my machine.

**Comment by xavierleroy** [comment]
It's a "gotcha" in Menhir's installation procedure, actually.  (I got bitten too.)  If you install Menhir with USE_OCAMLFIND=false, but Menhir was compiled without this option, `menhir --table --suggest-comp-flags` produces the wrong answer.  I'll make suggestions to @fpottier for improving this.

Concerning "no root privileges on a Linux server", that's exactly the job for OPAM (opam.ocaml.org): by default it installs everything in your home dir.

**Comment by andrew-appel** [comment]
Indeed.  After revewing this, J.-M. Madiot explained to me how to use OPAM in this situation.

**Comment by fpottier** [comment]
Thanks for reminding me of this issue. It should be fixed in the next release of Menhir.
