### ISSUE TITLE
Makefile does not install clightgen

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#82]
The Makefile has an "install" target to put "ccomp" into a user-specified bin directory,
but there is no corresponding installer for clightgen.  
[CompCert 2.6 distribution]

**Comment by bschommer** [comment]
There is a new configuration option added in commit 69d6a2c1e08e6169af95bf895d6b0380edb0d081 that enables the build and install of `clightgen` for the `make` targets `all` and `install`.
