### ISSUE TITLE
I have found a minor omission in the way compcert dumps its rtl tree: 

### ISSUE THREAD

**Issue by jrrk2** [AbsInt/CompCert#83]
I have found a minor omission in the way compcert dumps its rtl tree.
Obviously it is not very nice to find bad operators being dumped for
supposedly validating translations of a source code. I am sure you will
have no difficulty reproducing the problem, but if necessary I can send a test case.

jrrk2@serenity CompCert-2.6]$ diff -u ia32/PrintOp.ml{~,}
--- ia32/PrintOp.ml~    2015-12-21 09:09:21.000000000 +0000
+++ ia32/PrintOp.ml    2016-01-08 12:11:45.160542829 +0000
@@ -119,6 +119,9 @@
   | Omakelong, [r1;r2] -> fprintf pp "makelong(%a,%a)" reg r1 reg r2
   | Olowlong, [r1] -> fprintf pp "lowlong(%a)" reg r1
   | Ohighlong, [r1] -> fprintf pp "highlong(%a)" reg r1
+  | Onot, [r1] -> fprintf pp "not(%a)" reg r1
+  | Omulhs, [r1;r2] -> fprintf pp "mulhs(%a,%a)" reg r1 reg r2
+  | Omulhu, [r1;r2] -> fprintf pp "mulhu(%a,%a)" reg r1 reg r2
   | Ocmp c, args -> print_condition reg pp (c, args)
   | _ -> fprintf pp "<bad operator>"

[jrrk2@serenity CompCert-2.6]$

**Comment by xavierleroy** [comment]
Apologies for the late answer, and thanks for the report.  This issue is fixed by commit [d58c35e].
