### ISSUE TITLE
many temporary files

### ISSUE THREAD

**Issue by helloqirun** [AbsInt/CompCert#88]
With the current version, when I invoke ccomp -interp -fall a.c, it may generate many temporary files like
compcertb8d6b5.i in my temp folder. Those files remain there when ccomp quits.

The issue is gone when I revert to commit 54effdc2bae11f441a34465754e9e43c44b41df9.

**Comment by bschommer** [comment]
Should be fixed by commit 773058e7e21fa76097000bec6f1b9ff7e51d3b84.
